### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by ttorjan** [sksamuel/hoplite#108]
Just checking if there would be interest in making hoplite work on Android?

I could probably do it as part of my current project, since I would like to use hoplite, but just wanted to check before I start on it.

From a brief look, I've found the following issues that need to be resolved (there may be more, of course):

- FileSource needs to support a third type of data. The reason is that only very recent Android SDKs have support for Paths and most Android data will be in the assets store anyway. I would propose a kind of "GenericFileSource" with a constructor that takes an InputStream and extension-string, so it could be used for "anything". Alternatively, perhaps FileSource could be made open for extensions, so users can add any kind they want?
- EnvVarProcessor has a regexp that Android thinks is invalid. I'm expecting this will just be a matter of changing it slightly.
- javax.security does not exist in Android. I would propose to move those Decoders to a separate lib, similar to how Arrow is handled

**Comment by sksamuel** [comment]
We could probably make the project multiplatform with these changes.

**Comment by ttorjan** [comment]
Would you like me to prepare a PR with the above suggestions for review? It would also make it possible to add some more decoders to an android-project that can handle things like ColorStateList and other Android-specific types.

**Comment by sksamuel** [comment]
Yes, sounds good. We can add an android specific module as a further PR.

**Comment by runandrew** [comment]
@ttorjan @sksamuel  Does anyone have an example of using this library in Android? Specifically, being able to read from an InputStream due to the limitation of only being able to get files from the assets folder via an InputStream. Thanks!

**Comment by sksamuel** [comment]
You can pass in a resource file, or a stream that you load yourself, so you
should be able to make it work ?

**Comment by runandrew** [comment]
Thanks, I got it to work. I extended the ConfigSource class to add an option to pass in a stream.

**Comment by sksamuel** [comment]
Great.
