### ISSUE TITLE
load config from stream or stream

### ISSUE THREAD

**Issue by lizelive** [sksamuel/hoplite#114]

**Comment by sksamuel** [comment]
Can you expand ?

**Comment by sksamuel** [comment]
We can't load from a stream because we don't know the type of the data (json yaml etc).

**Comment by lizelive** [comment]
Their could be a parameter that specifies the mime type

**Comment by sksamuel** [comment]
Yes good idea.

**Comment by sksamuel** [comment]
Ok added this to master. Will be in the next release.
