### ISSUE TITLE
Incompatibility issue with kotlinx.serialization

### ISSUE THREAD

**Issue by venhuizen** [sksamuel/hoplite#136]
When a class is marked with the `@Serializable` annotation an error is thrown when loading the yaml file.  

> Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'com.example.Configuration' because:

        - 'seen1': Missing from config

        - 'example': - Could not instantiate 'com.example.ClientConfiguration?' because:

            - 'seen1': Missing from config

            - 'serializationConstructorMarker': Unable to locate a decoder for class kotlinx.serialization.SerializationConstructorMarker

        - 'example2': - Could not instantiate 'com.example.Configuration2' because:

            - 'seen1': Missing from config

            - 'serializationConstructorMarker': Unable to locate a decoder for class kotlinx.serialization.SerializationConstructorMarker

        - 'serializationConstructorMarker': Unable to locate a decoder for class kotlinx.serialization.SerializationConstructorMarker
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:172)
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:24)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
	at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:170)

**Comment by sksamuel** [comment]
How are you adding @Serializable to a class?
The kotlin one is internal only, and java.io.Serializable is an interface.

**Comment by venhuizen** [comment]
I am adding kotlin.reflect.Serializable as described in the https://github.com/charleskorn/kaml project.

**Comment by geomagilles** [comment]
Same issue. Trying to add Kotlin @Serializable to the config data classes => exeception
