### ISSUE TITLE
Preprocessors are activated for DataClass nodes only

### ISSUE THREAD

**Issue by Sulion** [sksamuel/hoplite#138]
Documentation states: 

> EnvVarPreprocessor: Replaces any strings of the form ${VAR} with the environment variable $VAR if defined. 

However, this is not true. Consider following config class: 

    data class Config(
        val someVar: String, 
        val freeFromSubConfig: Map<String, String>
    )

and the corresponding yml:

    someVar: ${VAR1:-varvar}
    freeFromSubConfig: 
        option1: ${OPTION1:-optionoption}

Now, `someVar` will be substituted, because the encompassing MapNode is processed by DataClassDecoder. `option1`, on the other hand, will not be expanded, as it's processed by `MapDecoder`, which ignores pre-processors: 

      override fun safeDecode(node: Node,
                          type: KType,
                          context: DecoderContext): ConfigResult<Map<*, *>> {
    require(type.arguments.size == 2)

    val kType = type.arguments[0].type!!
    val vType = type.arguments[1].type!!

    fun <K, V> decode(node: MapNode,
                      kdecoder: Decoder<K>,
                      vdecoder: Decoder<V>,
                      context: DecoderContext): ConfigResult<Map<*, *>> {

          return node.map.entries.map { (k, v) ->
            kdecoder.decode(StringNode(k, node.pos), kType, context).flatMap { kk ->
              vdecoder.decode(v, vType, context).map { vv ->
                kk to vv
              }
            }
          }.sequence()
            .mapInvalid { ConfigFailure.CollectionElementErrors(node, it) }
            .map { it.toMap() }
        }

        return context.decoder(kType).flatMap { kdecoder ->
          context.decoder(vType).flatMap { vdecoder ->
            when (node) {
              is MapNode -> decode(node, kdecoder, vdecoder, context)
              else -> ConfigFailure.UnsupportedCollectionType(node, "Map").invalid()
            }
          }
        }
      }
    }

**Comment by sksamuel** [comment]
The data class decoder runs the preprocessor and then sends the result to its children, so the map decoder should see the already preprocessed values. This wouldn't be the case if the entry point was something other than a data class decoder, eg a custom decoder or a sealed class.

I'll move the preprocessor fold into the config loader class.

**Comment by Sulion** [comment]
`EnvVarPreprocessor` skips all nodes that aren't StringNodes, and doesn't go down the tree level for MapNode which isn't data class. I must admit, I haven't read the code closely enough to know why.

I just thought you'd better know about this. I'd like to come up with the fix, but not sure if it'll be soon enough.

**Comment by sksamuel** [comment]
Fixed in 1.3.0
