### ISSUE TITLE
ConfigLoader cannot load default Decoder or Parser registries

### ISSUE THREAD

**Issue by AvlWx2014** [sksamuel/hoplite#142]
When instantiating a `ConfigLoader` instance, default values for `decoderRegistry` and `parserRegistry` are loaded with a `ServiceLoader`. 

The `ServiceLoader` implementation by default uses the `ClassLoader` returned by `Thread.currentThread().getContextClassLoader()` to load classes at runtime.

In cases where the `ClassLoader` returned by these means belongs to a "parent" application (e.g. an application which manages 3rd party plugins in its own process space), the default `decoderRegistry` and `parserRegistry` come back empty. 

This leads to consistent `EmptyDecoderRegistry` errors being thrown when calling `loadConfigOrThrow` (or returned in the case of `loadConfig`) even when working primarily with primitive types and objects supported out of the box with Hoplite.

**Comment by AvlWx2014** [comment]
I have implemented a patch for consideration, but do not have permissions to the project to push a branch and open a PR. I can Fork the repository, or post the code here. It's a small patch, but could definitely be expanded upon.

**Comment by sksamuel** [comment]
The typical github approach is to fork, push and create a PR.

**Comment by AvlWx2014** [comment]
Thanks, I will do that.
