### ISSUE TITLE
GraalVM support

### ISSUE THREAD

**Issue by krisgerhard** [sksamuel/hoplite#154]
It seems that it is not possible to use this dependency in a project which wants to build as a GraalVM native image.

I get an error `Can only decode into data classes`.

**Comment by sksamuel** [comment]
Please try  1.3.3

**Comment by KrisGerhard** [comment]
No resolved yet.
Issue on Quarkus' GitHub: https://github.com/quarkusio/quarkus/issues/11603

**Comment by sksamuel** [comment]
Worth adding to the readme?
