### ISSUE TITLE
Ktor docs

### ISSUE THREAD

**Issue by dotCipher** [sksamuel/hoplite#156]
My question wasn't really answered in https://github.com/sksamuel/hoplite/issues/19 and I believe it was closed prematurely.  Is the path forward to read the source and determine how to integrate with Hoplite if using Ktor?  Or can you provide with at least some form of code sample to use YAML via Hoplite instead of HOCON via default Ktor?

**Comment by sksamuel** [comment]
The ktor module has been removed because it proved too flaky to integrate, and really only saves 3/4 lines of code.
What I do is have an application.conf that contains only the bare minimum:

```
ktor {
  deployment {
    port = 8087
  }
  application {
    modules = [ com.xxx.KtorKt.main ]
  }
}
```

And then the rest in hoplite config.

**Comment by dotCipher** [comment]
Ahh ok I see what you mean, there is no way to just override the default behavior of ktor to use a different config provider instead?

**Comment by sksamuel** [comment]
Yeah you can, which is what I had done originally but it's pretty hacky.

I would just load a hoplite config and then programmatically create the
ktor instance rather than using config at all.

**Comment by dotCipher** [comment]
Interesting, the ktor team hasn't provided any 'non-hacky' mechanisms you've noticed yet then? That's unfortunate 😢

**Comment by sksamuel** [comment]
Closed because ktor config isn't part of hoplite.
