### ISSUE TITLE
ClasspathPropertySource?

### ISSUE THREAD

**Issue by H4xX0r1337** [sksamuel/hoplite#161]
I'm planning on using this library in one of my projects. I'm planning to put the base configuration in my classpath / inside the jar and let the user override it with a local file. Would that be possible?  
Oh, and would something like setting a default value on a class work?

**Comment by sksamuel** [comment]
Yep, you can use a local file to override. That's what I do.

**Comment by H4xX0r1337** [comment]
@sksamuel I meant is it possible to have the config in the jar itself? I want to have most of the config there, and only the parts that the user wants to oberwrite should be in the file.

**Comment by sksamuel** [comment]
You can put config anywhere you want.
Have a file called application-most-of-it.yml in your jar, and then another
called local-user-overrides.yml and then just reference them in reverse
order (local one first) when you create config.
Any values in the local file will override the other file.

**Comment by H4xX0r1337** [comment]
@sksamuel but how? There is no ClasspathPropertySource, how would you specify the file inside the jar?

**Comment by sksamuel** [comment]
You just use the normal resource source, which will look anywhere on the
classpath.

**Comment by H4xX0r1337** [comment]
@sksamuel so ConfigLoader().loadConfig<MyConfig>("/test.yml")? Or do i have to use withPropertySource somehow?

**Comment by sksamuel** [comment]
That's enough, and pass in more than one string for more than one resource.

**Comment by H4xX0r1337** [comment]
@sksamuel If that syntax is used for adding a classpath file, how would you then add a file external that is not in the cp? This question sounds stupid but i'm legit confused

**Comment by sksamuel** [comment]
Sorry I thought both files lived in the classpath, one in a jar and one
just as a file.

If one file is external, can you do this:

ConfigLoader.Builder()
  .addPropertySource(ConfigFilePropertySource(ConfigSource.FileSource("/home/sam/foo")))
  .addPropertySource(ConfigFilePropertySource(ConfigSource.ClasspathSource("/resource_in_classpath")))
  .build().loadConfigOrThrow<MyConfig>()


It's not super intuitive, and we should probably add more helper methods to
do this easier.

**Comment by H4xX0r1337** [comment]
@sksamuel Oh yeah that indeed looks a bit messy, but I'm glad this is possible. Small question: Is it possible to change a configuration property via the library while maintaining comments?

**Comment by sksamuel** [comment]
What do you mean by maintaining comments? Do the config files support
comments? If so, yes, just whatever the underlying format supports (json,
yaml whatever).

**Comment by H4xX0r1337** [comment]
@sksamuel i mean, is it possible to programmatically write a property to the config, without erasing the comments already in the file?

**Comment by sksamuel** [comment]
Hoplite doesn't do any persistence of config.

**Comment by H4xX0r1337** [comment]
@sksamuel i didn't exactly understand but nvm, I think you can't write to the config via code and if then it isn't exactly needed.

**Comment by sksamuel** [comment]
If you use 1.3.5 you can do this now:

```kotlin
 val config = ConfigLoader.Builder()
       .addPreprocessor(ParameterStorePreprocessor)
       .addPropertySource(PropertySource.resource("/application-$env.yml", true))
       .addPropertySource(PropertySource.resource("/application.yml", false))
       .build()
       .loadConfigOrThrow<<MyConfig>()
```

Which I think is quite neat.

**Comment by H4xX0r1337** [comment]
@sksamuel That doesn't quite work as I thought it would. If the property isn't there in one file, I expect the second file to be queried. But it currently only checks if the file exists and only uses the second file if it doesn't. How would I do that?

**Comment by sksamuel** [comment]
It does do that, if I understand you correctly.

The config loader will take each source it finds, and collapse them together, overlaying them, with the first source taking priority.

So:

file1: a = foo, c = baz
file2: a = F, b = G, c =H

The resolved config would be, a = foo, b = G, c = baz

And if you added in files that didn't exist, and set optional to true, they would just be skipped.

**Comment by H4xX0r1337** [comment]
@sksamuel oh you're right, it actually does that if all files contain settings, but it still throws if the file is completely empty / comments only. That would be handy to show the settings the user could theoretically overwrite.

**Comment by sksamuel** [comment]
That sounds like an issue with the actual yml / json parser then, but we can add an option to catch it and ignore.
