### ISSUE TITLE
Catching exceptions from DataClassDecoder

### ISSUE THREAD

**Issue by smcbn** [sksamuel/hoplite#165]
I upgraded from 1.3.2 to 1.3.4 to take advantage of the builder fix in #157 but the change for #155 that is also in 1.3.4 breaks validation that I had within a data class

```
    data class Config (
            val field1: SomeType,
            val field2: SomeType
    ) {
        check (/* do some value check */) { "errorMsg" }
    }
```
When the above check failed I could catch the exception and log the error correctly however now the Exception from my `check` is caught in the code from #155. The message from the exception is not stored but the decoder is marked as failed and so throws a ConfigException [here](https://github.com/sksamuel/hoplite/blob/master/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/ConfigLoader.kt#L300) but the message in the exception has no relevance and doesn't match the actual error at all.

Could the original exception message from the `check` be stored and returned?

**Comment by sksamuel** [comment]
Make sense.

**Comment by sksamuel** [comment]
1.3.6 has been released with this change.
