### ISSUE TITLE
Support Yaml merging (inheritance)

### ISSUE THREAD

**Issue by Virtlink** [sksamuel/hoplite#167]
In configuration files it would be very useful to be able to define a default set of values and let individual objects inherit/override some of those values, as shown in [this example](https://dmitryrck.com/how-to-use-inheritance-in-yaml-files/). This is a feature supported by the YAML format and SnakeYaml, but not by Hoplite. Instead, I get:

```
Invalid YAML event Alias at  in 'reader', line 10, column 7:
    - <<: *default
          ^
java.lang.UnsupportedOperationException: Invalid YAML event Alias at  in 'reader', line 10, column 7:
    - <<: *default
          ^
	at com.sksamuel.hoplite.yaml.TokenProduction.invoke(YamlParser.kt:95)
```

This would be a very useful feature to have in this configuration library, for example when configuring a list of objects with similar values. Here is [an example of merging](https://yaml.org/type/merge.html).

**Comment by sksamuel** [comment]
Snakeyml says they removed merging functionality.

**Comment by sksamuel** [comment]
Looks like it's been removed completely from yaml 1.2

**Comment by Virtlink** [comment]
Hmm... I didn't know that. Apparently it is an extension to Yaml ([source](https://stackoverflow.com/a/47203224/146622)). 
However, Snakeyaml's latest docs [still mention it](https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-merge) and I can't find anything about removing merging in their [release notes](https://bitbucket.org/asomov/snakeyaml/wiki/Changes). But I understand if you don't want to spend time supporting something that might be removed or replaced.

**Comment by sksamuel** [comment]
In 1.2 it looks like snakeyml was renamed to snakeyml engine.
The merge removal is documented here:
https://bitbucket.org/asomov/snakeyaml-engine/wiki/Documentation#markdown-header-merge

**Comment by Virtlink** [comment]
Okay, thanks for the info.
