### ISSUE TITLE
possible to use hoplite without arrow?

### ISSUE THREAD

**Issue by 2x2xplz** [sksamuel/hoplite#174]
Was trying to reduce the size of my JAR, realized `arrow` was a large dependency traced back to hoplite. I'm all about Functional Programming but in this case, I was using exactly one Arrow function, `valueOr` (to extract a valid Config from ConfigResult). I modified the code to not use any Arrow functions, did a clean build and re-compile, unfortunately Arrow is still in my JAR. Is it safe to `exclude` (via Gradle) or does Hoplite rely on it internally? Any other way to specify not to include it in the JAR at all?

**Comment by sksamuel** [comment]
Hoplite should have no dependency on arrow.  Are you sure it's hoplite
bringing it in.

**Comment by 2x2xplz** [comment]
OK, I was on an old version, before you modular-ized `hoplite-arrow` to its own package. With the latest hoplite core, there are no references to Arrow and my JAR is significantly smaller. Thanks.

```
|    +--- com.sksamuel.hoplite:hoplite-core:1.1.2
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.4.0 (*)
|    |    +--- io.arrow-kt:arrow-core-data:0.10.0
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21 -> 1.4.0 (*)
|    |    |    \--- io.arrow-kt:arrow-annotations:0.10.0
|    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 -> 1.4.0 (*)
|    |    |         \--- io.kindedj:kindedj:1.1.0
|    |    +--- io.arrow-kt:arrow-validation:0.10.0
|    |    |    +--- io.arrow-kt:arrow-core:0.10.0
|    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21 -> 1.4.0 (*)
|    |    |    |    +--- io.arrow-kt:arrow-annotations:0.10.0 (*)
|    |    |    |    \--- io.arrow-kt:arrow-core-data:0.10.0 (*)
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21 -> 1.4.0 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-reflect:1.3.50 -> 1.4.0 (*)
|    +--- com.sksamuel.hoplite:hoplite-yaml:1.1.2
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.4.0 (*)
|    |    +--- io.arrow-kt:arrow-core-data:0.10.0 (*)
|    |    +--- io.arrow-kt:arrow-validation:0.10.0 (*)
|    |    +--- com.sksamuel.hoplite:hoplite-core:1.1.2 (*)
|    |    \--- org.yaml:snakeyaml:1.24
```

**Comment by sksamuel** [comment]
Ah cool.
