### ISSUE TITLE
I tried to read YAML config from filesystem and it won't compile

### ISSUE THREAD

**Issue by anysolo-dlong** [sksamuel/hoplite#182]
All the unit tests in the repo tests only reading config from resources, not from the file system.
Could you provide a working code reading config from the filesystem?
ConfigLoader.Builder().addSource(YamlPropertySource.file(File("filename.yaml"))).build()
or
ConfigLoader.Builder().addSource(YamlPropertySource.file("filename.yaml")).build()
or
ConfigLoader.Builder().addSource(YamlPropertySource("filename.yaml")).build()

**Comment by sksamuel** [comment]
Something like this:

```
    ConfigLoader.Builder()
      .addSource(ConfigFilePropertySource(ConfigSource.FileSource(path)))
      .build()
      .loadConfigOrThrow<Test>()
```

**Comment by anysolo-dlong** [comment]
> addSource(ConfigFilePropertySource(ConfigSource.FileSource(path)))
>       .build()

Thanks. It worked.
