### ISSUE TITLE
addFileExtensionMapping method does not work in my  scenario

### ISSUE THREAD

**Issue by jarekratajski** [sksamuel/hoplite#184]
Was getting error:
```
Could not detect parser for file extension '.yml' - available parsers are {props=com.sksamuel.hoplite.parsers.PropsParser@209da20d, properties=com.sksamuel.hoplite.parsers.PropsParser@209da20d}
```
In my build services file (manifest/ `Parsers`) were overwritten by default values (`com.sksamuel.hoplite.parsers.PropsParser`).

Initially, I did not want to fix "services" files as I do not want to depend on "classloader" anyhow.
So I created this snippet:
```
 ConfigLoader.Builder().addFileExtensionMapping("yml", yamlParser).also { println("added yml support 1") }
        .addSource(PropertySource.path(configPath.resolve("oauthConfig.yml")))
        .addDecoder(VMapDecoder())
        .build()
        .loadConfig<OauthConfig>()
```

However that did not work: (producing `Could not detect parser for file extension '.yml`)
Because add source is calling this code in Hoplite:
```
class ConfigFilePropertySource(
  private val config: ConfigSource,
  private val parserRegistry: ParserRegistry = defaultParserRegistry(), //NOTICE: default value used here (parsers from classloader)
  private val optional: Boolean = false
) 
```
Later,  only this parserRegistry is effectively used.

Because of that `addFileExtensionMapping("suffix", xyx)` is mostly useless. 
Version was 1.3.10 - but I do not see changes in that aspect in newer code.

**Comment by sksamuel** [comment]
Something like this should work:

```kotlin
    val myPath = configPath.resolve("oauthConfig.yml")
    val parsers = defaultParserRegistry().register("yml", yamlParser)
    ConfigLoader.Builder()
      .addSource(ConfigFilePropertySource(ConfigSource.PathSource(myPath), parsers))
      .addDecoder(VMapDecoder())
      .build()
      .loadConfig<OauthConfig>()
```

**Comment by Pyeroh** [comment]
I met the same problem, but I figured out why : I'm using the maven shade plugin.  
If you're in the same situation, you may find [that link](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer) interesting. If you're using the shadow plugin for Gradle, [this link](https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files) may suit your needs.

**Comment by NiewidzialnyCzlowiek** [comment]
I've enountered the same issue as @jarekratajski. I managed to create a working jar using the shadow plugin with mergeServiceFiles() option as @Pyeroh suggested. For now this solution is fine, but it would be great if you made it work for standard gradle jar task.
I used the version 1.3.13
