### ISSUE TITLE
Missing from config error all times

### ISSUE THREAD

**Issue by lebedynskyi** [sksamuel/hoplite#188]
**Precondition:**
**This is my simple Yaml:**
```
debug: true

server:
  ip: 127.0.0.1
  serverPort: 2200
  gameServerIp: 127.0.01
  gameServerPort: 3300
```

**This is my data clases:**
```
data class ServerConfig(
    val ip: String,
    val serverPort: String,
    val gameServerIp: String,
    val gameServerPort: String,
)

data class LoginConfig(
    val debug: Boolean,
    val server: ServerConfig
)
```

**And this is how i use it:**

```
val configStream= {}::class.java.getResourceAsStream("MainConfig.yaml")
val config = ConfigLoader.Builder()
        .addSource(PropertySource.stream(configStream, "props"))
        .build()
        .loadConfigOrThrow<LoginConfig>()
```
**Error:**
```
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'model.config.LoginConfig' because:

        - 'server': - Could not instantiate 'model.config.ServerConfig' because:

            - 'ip': Missing from config

            - 'serverPort': Missing from config

            - 'gameServerIp': Missing from config

            - 'gameServerPort': Missing from config
```

**Description**
Now it throws error above.  But if I use nullable fields in **ServerConfig** the config will be created but with null inside **ServerConfig**

**Comment by sksamuel** [comment]
What is "configText" in this case ?

**Comment by lebedynskyi** [comment]
> What is "configText" in this case ?

This is a stream to a a file in **Kotlin resource folder**

**Comment by sksamuel** [comment]
Which contains the config you pasted?

**Comment by lebedynskyi** [comment]
> Which contains the config you pasted?

Exactly. I open it via:
`  val configText = {}::class.java.getResourceAsStream("MainConfig.yaml")`

**Comment by lebedynskyi** [comment]
@sksamuel 
I've updated origfinal topic. Please reccheck itt

**Comment by sksamuel** [comment]
You are telling the property source to parse the file as props, when you are passing in a yaml file.
You should do this instead:
`PropertySource.stream(configStream, "yaml"))`

**Comment by lebedynskyi** [comment]
@sksamuel  thanks for help me.. 

I also noticed that I should use something another. In this case I face next issue:
```
Could not detect parser for file extension '.yaml' - available parsers are {props=com.sksamuel.hoplite.parsers.PropsParser@2145433b, properties=com.sksamuel.hoplite.parsers.PropsParser@2145433b}
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:299)
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:20)
```

**Comment by sksamuel** [comment]
This is because you haven't added `hoplite-yaml` to your build.

**Comment by lebedynskyi** [comment]
@sksamuel  I thought i was wrong in this.. You helped me. It fixed the issue. 

**Please update readme a little bit to make it more clear that we need use not only core library and some plugin for it..**
