### ISSUE TITLE
How to use with ktor docs 

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/hoplite#19]

**Comment by dotCipher** [comment]
Any update on this? I'd be curious to see how to use this lib with ktor as I stumbled on it via awesome-kotlin

**Comment by sksamuel** [comment]
Yeah I just need to write it up. The ktor module just replaces the application.conf you create, but the rest of the config can go through hoplite already.

**Comment by dotCipher** [comment]
Any simple examples that I can use to start with? Still a little unsure of how to use it.

**Comment by dotCipher** [comment]
Any update on this?

**Comment by sksamuel** [comment]
Do you want to know how to replace application.conf from ktor, or how to use general config in a web app? @dotCipher

**Comment by dotCipher** [comment]
Specifically replacing the application.conf from ktor with hoplite

**Comment by psilos** [comment]
Hello, I would be interested to use Hoplite for Ktor configuration as well, but as far as I can see the integration with ktor is one way. 

The main benefit for using hoplite is the ability to dynamically bind my configuration to a Data Class during start-up time or fail the application early. And then use the data class throughout the application. 

I don't see a clean way to do this with hoplite-ktor atm, I believe the current integration is to allow Ktor to load configuration in different formats other than the default HOCON. 

Is this the case @sksamuel ?

**Comment by sksamuel** [comment]
Yes, there's not a huge amount to gain, other than if you're using yaml,
you don't also need a hocon file.
In retrospect it probably isn't that useful.

**Comment by psilos** [comment]
No worries, thanks for clarifying, I will still love hoplite for application configuration but may need to read properties a second time.
