### ISSUE TITLE
Something is wrong with 1.3.14 release

### ISSUE THREAD

**Issue by tagantroy** [sksamuel/hoplite#193]
You published 1.3.14 released 15 minutes ago, but tag for this release created one week ago and jars with this version already present in maven central. https://github.com/sksamuel/hoplite/releases/tag/v1.3.14 and https://repo1.maven.org/maven2/com/sksamuel/hoplite/hoplite-core/1.3.14/
Can you bump version and upload one more time?

**Comment by sksamuel** [comment]
I just hadn't added the release to github.

**Comment by sksamuel** [comment]
I'l do a 1.3.15 release with your PR.
