### ISSUE TITLE
How to distinguish between no property source and property source with invalid syntax?

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#200]
When loading the config, I currently see no (easy) way to distinguish between

1. errors because none of the (optional) property sources was available, and
2. errors because the syntax of the config in an existing property source was wrong.

I'm currently experimenting with some really hacky code that looks like

    val sources = listOfNotNull(
        args?.takeIf { it.keys.any { key -> key.startsWith("ort.") } }?.let { argumentsSource(it) },
        configFile?.takeIf { it.isFile }?.let { PropertySource.file(it) },
        resource?.takeIf { OrtConfiguration::class.java.getResource(resource) != null }?.let { PropertySource.resource(it) }
    )

    // Missing sources are no syntax error, so exit early here to avoid Holite to complain.
    if (sources.isEmpty()) return OrtConfiguration()

    val builder = ConfigLoader.Builder()
        .addSources(sources)
        .build()

    val result = builder.loadConfig<OrtConfigurationWrapper>().getOrElse {
        // Complain about real syntax errors here.
    }

Any suggestion how to do this in a better way?

**Comment by sschuberth** [comment]
Nevermind, looks like the issue I was seeing was not due to `.loadConfig<OrtConfigurationWrapper>()` but due to a `.map { it.ort }` (that I accidentally omitted from the above example). The *mapping* failed when the result was invalid due to no sources being present. But that is something I could easily fix by doing the mapping / unwrapping *after* `getOrElse {}`.

**Comment by sksamuel** [comment]
Ok glad you got a solution.

**Comment by sschuberth** [comment]
If you're interested, the key was basically this change: https://github.com/oss-review-toolkit/ort/pull/3731/commits/5949f68dd74ba6bfed63c86591b64282fe058790. Note how it moves the unwrapping from `result.map { it.ort }...` in th beginning to `.getOrElse { ... }.ort` in the end.
