### ISSUE TITLE
Using strict() throws an error loading config listing unused Environment Variables.

### ISSUE THREAD

**Issue by chris-ryan-square** [sksamuel/hoplite#201]
Using the following example:

application.yaml

```
foo:
   enabled: true
```

and this code

```
import com.sksamuel.hoplite.ConfigLoader
import com.sksamuel.hoplite.PropertySource

object Application {

    @JvmStatic
    fun main(args: Array<String>) {
        ConfigLoader.Builder()
            .addSource(PropertySource.resource("/application.yaml"))
            .strict()
            .build()
            .loadConfigOrThrow<Config>()
    }
}

data class Config(val foo: Foo)
data class Foo(val enabled: Boolean)
```

fails, with an error similar to:

```
Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:

    Config values were not used: PATH, ...snip...
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:335)
	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:20)
	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
	at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:332)
...
```

Can the Environment, System and UserSettings property sources be optional for strict?

Perhaps change strict() to accept override flags (with defaults matching current usage):

```
strict(
  includeEnvironmentVariables = true, 
  includeSystemProperties = true,
  includeUserSettings = true
)
```

**Comment by sksamuel** [comment]
I think strict on env's makes no sense actually, as there's always likely to be env's no used.
I mean hoplite doesn't control the entire env right :)
Same for system properties.
I'm surprised the tests didn't catch this.
It should only apply to files imo.

**Comment by chris-ryan-square** [comment]
I tend to agree, but I wasn't ensure of the overall intent.

**Comment by sksamuel** [comment]
I consider this a bug. I've added a test case that duplicates the issue:
https://github.com/sksamuel/hoplite/pull/202

I'll add a fix, it's not super trivial as it means tracking where the value originally came from since the strictness is enforced later.

**Comment by chris-ryan-square** [comment]
If you're adding tracking, would this mean we could "ask" for a particular config item, where it actually got set from?  I could see this as a great debugging tool - output the loaded config tree, annotated with the location of what set each item.

**Comment by sksamuel** [comment]
That's a great idea.

**Comment by sksamuel** [comment]
I think I will need to release 2.0 with an improved config model. Which contains at each node where that value came from. Then strict can work, and debugging can work too.

**Comment by JohnNewman1** [comment]
Hi there, I am having the same issue with env variables, I really like the use of strict mode however due to it picking up the env variables I am unable to use it. Any idea if this is in the horizon to fix?

**Comment by sksamuel** [comment]
Yes, I was waiting for Kotlin 1.5 to come out to make these changes, and
release a 2.0 version (since it will require breaking some internals, which
may affect some people who write custom decoders).
Since Kotlin 1.5 came out yesterday I'll do this work at the weekend and
release then.

**Comment by JohnNewman1** [comment]
Great Thanks for your swift reply :)

**Comment by chris-ryan-square** [comment]
Still need this.  Any progress on the 2.0 version?

**Comment by sksamuel** [comment]
Yes i have a lot done locally and want to release with kotlin 1.6 as
durations will be no longer experimental.

**Comment by sksamuel** [comment]
This is now implemented in master.

**Comment by aviadmini** [comment]
I'm getting unused errors for env source in v2.0.2. Did this version not receive the fix?
` Config value 'path' at (env) was unused` same for other env vars in the container

**Comment by sksamuel** [comment]
Yes, you're not using the env vars right?

**Comment by aviadmini** [comment]
I am using env vars, and I want to be able to use `strict()` at the same time. 

My config loader builder looks like this
```kotlin
private val configLoader = ConfigLoader {
    strict()
    addEnvironmentSource()
}
```

**Comment by bt-wil** [comment]
I'm running into the same situation using `v2.1.5`.  The use case is exactly the same with env-vars overriding the file-vars with strict mode.

```
val config =
    ConfigLoaderBuilder.default()
        .apply {
            addEnvironmentSource()
            if (configFile != null) {
                addFileSource(File(configFile))
            }
        }
        .strict()
        .build()
        .loadConfigOrThrow<...>()

...

Config value 'home' at (env) was unused
Config value 'javaHome' at (env) was unused
```

The approach that I took was to only look for env vars with a prefix.
```
EnvironmentVariablesPropertySource(
    useUnderscoresAsSeparator = true,
    allowUppercaseNames = true,
) {
    System.getenv()
        .filterKeys { it.startsWith(envPrefix) }
        .mapKeys { it.key.removePrefix(envPrefix) }
}
```
Is there a better approach to this where it does not throw errors with unused env variables?

**Comment by sanyarnd** [comment]
For anyone still struggling with it.



```kotlin
/** Parse configuration file to specified POJO class */
fun <T : Any> parseConfig(configFile: Path, clazz: KClass<T>): T {
    val path = configFile.toAbsolutePath()
    logger.debug(a("file", path)) { "Parsing configuration file..." }
    val config = ConfigLoaderBuilder.default()
        .addSource(FilteredEnvironmentVariablesPropertySource(clazz))
        .addSource(PropertySource.path(path))
        .strict()
        .build()
        .loadConfigOrThrow(clazz, emptyList())
    logger.debug(a("file", path)) { "Parsing complete!" }
    return config
}

private class FilteredEnvironmentVariablesPropertySource<T : Any>(configClass: KClass<T>) : PropertySource {
    // get names of all fields in a config
    private val configTopFields = configClass.declaredMemberProperties.map(KProperty1<T, *>::name)

    // official separators for env variables
    private val separators = listOf(".", "__")

    // use default env property source
    private val d = EnvironmentVariablesPropertySource(useUnderscoresAsSeparator = true, allowUppercaseNames = true) {
        // filter env keys by prefix and follow official convention ("." and "__")
        System.getenv().filterKeys { envKey ->
            configTopFields.any { topKey ->
                val fullMatch = envKey.equals(topKey, ignoreCase = true)
                val sepMatch = separators.any { sep -> envKey.startsWith("$topKey$sep", ignoreCase = true) }
                fullMatch || sepMatch
            }
        }
    }

    override fun node(context: PropertySourceContext): ConfigResult<Node> = d.node(context)
    override fun source(): String = d.source()
}
```

**Comment by sksamuel** [comment]
> 

I think here the solution is don't use the env property source.
The built in env param mapper will do the ${name} replacements.

**Comment by sksamuel** [comment]
> I am using env vars, and I want to be able to use `strict()` at the same time.
> 
> My config loader builder looks like this
> 
> ```kotlin
> private val configLoader = ConfigLoader {
>     strict()
>     addEnvironmentSource()
> }
> ```
> 
> Edit: I guess there's no good way to check unused for env vars. My use case was usage of a file config that can be overridden by env vars. The example above is the simplified version that had the issue reproducible.

I think here the solution is don't use the env property source.
The built in env param mapper will do the ${name} replacements.

**Comment by sksamuel** [comment]
So then it's working, because you didn't use the env var right ?
Or are you saying what you what is a strict mode that ignores env vars.
