### ISSUE TITLE
Add a way to serialize / show the configuration

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#203]
There are cases when it's desirable to be able to show the active configuration to the user, in a format known to the user. So when e.g. using a HOCON `.conf` file and other configuration sources, it would be nice to be able to present the user a HOCON file that has all other configuration sources "baked in". For this, Hoplite would also need to be able to serialize configuration (to a string), not only to deserialize it.

Would you consider this to be in scope of Hoplite?

**Comment by sksamuel** [comment]
I guess for YML or JSON you can just take your config domain object and marshall it back out using jackson or whatever ? Not sure if hocon can do that?

**Comment by sschuberth** [comment]
HOCON *can* do that, see

https://github.com/oss-review-toolkit/ort/pull/3731/files#diff-2cb1c1ff53c3d3d7d17bf1faab771645251a06f3c6abe6cd714d937d6bac22d4R58

but the point that arose in the PR discussion was that we'd prefer not to do that by calling Jackson / config4k directly, but by the same same means (i.e. library used) as Hoplite to not introduce new direct dependencies.

**Comment by sksamuel** [comment]
I'm not sure it's worth adding a serialization function into this library, to just call the same method on another library. All it would be doing is passing through the method call.

**Comment by sschuberth** [comment]
I tend to agree, and that's what I had probably answered myself, but still wanted to hear your opinion. I'm closing this.
