### ISSUE TITLE
Yaml parser has to be explicitly added to Builder

### ISSUE THREAD

**Issue by XiangRongLin** [sksamuel/hoplite#204]
Im currently trying out the library and have the problem that it throws an error if i don't explicitly add the yaml parser from `hoplite-yaml` with `addFileExtensionMapping`.
In the Readme it mentioned that `For each format you wish to use, you must include the appropriate hoplite module on your classpath`. Is this more than just adding the dependecy to maven?

The error
`Could not detect parser for file extension '.yaml' - available parsers are {props=com.sksamuel.hoplite.parsers.PropsParser@29626d54, properties=com.sksamuel.hoplite.parsers.PropsParser@29626d54}` 

My pom.xml
``` xml
<dependency>
  <groupId>com.sksamuel.hoplite</groupId>
  <artifactId>hoplite-core</artifactId>
  <version>1.4.0</version>
</dependency>

<dependency>
  <groupId>com.sksamuel.hoplite</groupId>
  <artifactId>hoplite-yaml</artifactId>
  <version>1.4.0</version>
</dependency>
```

My code
``` kotlin
fun init() {
    val build = ConfigLoader
        .Builder()
        .addFileExtensionMapping("yaml", YamlParser())
        .build()
    this.config = build
        .loadConfigOrThrow<Config>("/config.yaml")
  }
```

**Comment by sksamuel** [comment]
Are you doing a fat-jar or shaded jar?

**Comment by XiangRongLin** [comment]
Yes I'm doing a far jar with uberjar. but i looked inside the jar and found the YamlParser.class inside it.

**Comment by sksamuel** [comment]
You're probably not merging the service files. See last comment on here: https://github.com/sksamuel/hoplite/issues/94

I will update the readme.

**Comment by XiangRongLin** [comment]
Yes that was it.

Adding the ServicesResourceTransformer to the maven-shade-plugin solved it
`<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>`
