### ISSUE TITLE
com.sksamuel.hoplite.ConfigException

### ISSUE THREAD

**Issue by Vladimir77715** [sksamuel/hoplite#206]
com.sksamuel.hoplite.ConfigException: Error loading config because:

    Could not detect parser for file extension '.json' - available parsers are {props=com.sksamuel.hoplite.parsers.PropsParser@72ade7e3, properties=com.sksamuel.hoplite.parsers.PropsParser@72ade7e3}

**Comment by chris-ryan-square** [comment]
Did you see: https://github.com/sksamuel/hoplite#supported-formats? - you'll need to add the **hoplite-json** module.

**Comment by sksamuel** [comment]
@Vladimir77715 did you fix this by following Chris's suggestion ?
