### ISSUE TITLE
ConfigAlias cannot identify layered path with dot in yaml

### ISSUE THREAD

**Issue by joey-yoonsung** [sksamuel/hoplite#207]
# My Indentation

### yaml
```
kafka:
  producer:
    bootstrap-servers: "localhost:9092,localhost:9093"
    topic: "demo-topic-event"
    client-id: "client"
    aks: "all"
  consumer:
    bootstrap-servers: "localhost:9092,localhost:9093"
    topic: "demo-topic"
    client-id: "client"
    group-id: "group"
    auto-offset-reset: "earliest"
```

### data class
```
data class ApplicationConfig(
    @ConfigAlias("kafka.producer")
    val kafkaProducerConfig: KafkaProducerConfig,
    @ConfigAlias("kafka.consumer")
    val kafkaConsumerConfig: KafkaConsumerConfig
) {
```

### Error message
```
Could not instantiate 'mypackage.ApplicationConfig' because:

        - 'kafkaProducerConfig': Missing from config

        - 'kafkaConsumerConfig': Missing from config
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:335)
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:20)
        at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
        at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:332)
```

### How can I resolve
I fix my yaml unfolding layered config to make it the same alias name.
```
kafka.producer:
  # blah
kafka.consumer:
  # blah
```

# Problem
I expect `ConfigAlias` will find sub-paths in `kafka` block and it matches with the dot-separated path as a string in alias annotation.
But It doesn't.

# Suggestion
How do we make that dot-separated path as a string in alias annotation can match a layered path in yaml?

If you agree with my suggestion. I want to make PR for it by myself.

Could you let me know for where source code I should refer to solve this issue?

**Comment by sksamuel** [comment]
This might require some reworking on the lookup structure. You're essentially wanting to search the entire tree when you hit @ConfigAlias but all it has access to is the data at that point.
