### ISSUE TITLE
Feature Request: automatic/periodic reload config from files

### ISSUE THREAD

**Issue by yogurtearl** [sksamuel/hoplite#212]
Sometimes config files are updated dynamically thru other outside tools. 

It would be nice if the was a way to either reload config automatically/periodically to pick up changes to config files. 
Maybe thru a `ConfigProvider`/`ConfigCache` abstraction, that checks if the config source has changes on some interval? 

The resulting config should still be strictly immutable, returning a new instance if/when the config changes. 

Related: 
`konf` offers `watchFile` 

https://github.com/uchuhimo/konf/blob/8aa88358b89f7ef2b124ee608b852a18a43aac7f/konf-core/src/main/kotlin/com/uchuhimo/konf/source/DefaultLoaders.kt#L212

**Comment by sksamuel** [comment]
I've thought about this before and wondered if it's out of scope of the library or if it should be in here.

**Comment by sksamuel** [comment]
We now have the hoplite-watch module to do this. Thanks to @ncarroll-grindr 
I still need to add docs but its pretty self explantory from the code.

**Comment by sksamuel** [comment]
Closing this because we have Reloadable config now.
