### ISSUE TITLE
unresolved env variable should throw an error

### ISSUE THREAD

**Issue by Stefanqn** [sksamuel/hoplite#215]
```
      data class C(val s: String)
      println(ConfigLoader.Builder()
        .addSource(YamlPropertySource("s: \${PATHX}"))
        .build()
        .loadConfigOrThrow<C>())
```
PATHX is not resolved, but the output is "C(s=${PATHX})" instead of an error

**Comment by sksamuel** [comment]
That's the design. If things don't exist it just falls through to the next tier. If nothing is there at all it won't resolve.
I guess the best thing to do would be to add an option that errors when env's are missing for those people who want that behavior (seems reasonable).

**Comment by sksamuel** [comment]
Add option to error if env is missing #216

**Comment by sksamuel** [comment]
Completed in master.
