### ISSUE TITLE
Version 1.4.4 is not released

### ISSUE THREAD

**Issue by frederic-kneier** [sksamuel/hoplite#218]
Version 1.4.4 is not available in Maven Central.

**Comment by Kernald** [comment]
It has been tagged, but not actually marked as a release on GitHub either - I guess that's why it hasn't been pushed.

**Comment by sksamuel** [comment]
I think something went wrong during the release. I've re-ran it. It should appear  soon at https://repo1.maven.org/maven2/com/sksamuel/hoplite/hoplite-core/
