### ISSUE TITLE
No decoders are registered

### ISSUE THREAD

**Issue by TSGSamu18** [sksamuel/hoplite#219]
Error:

> Exception in thread "main" com.sksamuel.hoplite.ConfigException: Error loading config because:
>     No decoders are registered
> 	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:338)
> 	at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:335)
> 	at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
> 	at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:335)
> 	at MainKt.main(Main.kt:81)

Main.kt:

```

data class Config(
  val mode: String
)

fun main(args: Array<String>) {

  val config = ConfigLoader().loadConfigOrThrow<Config>("/config.yaml")

}
```

config.yaml:

> mode: 'normal'

**Comment by sksamuel** [comment]
Are you creating a far jar ?

**Comment by TSGSamu18** [comment]
No, I'm only debugging my project.

[I've created a repository with an example.](https://github.com/TSGSamu18/hoplite-example/tree/main/src/main/kotlin) 

**NOTE** I've manually imported hoplite-core and hoplite-yaml.

**Comment by sksamuel** [comment]
If you are not using the pre-built jars, then you will need to register the
parser with the file type.

**Comment by sksamuel** [comment]
Did you get it working ?
