### ISSUE TITLE
Roadmap 2.0

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/hoplite#226]
- [x] #216
- [x] #267
- [x] #228
- [x]  #280
- [x] #281
- [x] #283

**Comment by datentyp** [comment]
Hi,

What are your thoughts on supporting more than one ConfigAlias? 

Thanks,

**Comment by sksamuel** [comment]
Yes that seems fine, kotlin 1.6 allows repeatable annotations.

**Comment by yogurtearl** [comment]
Is there a separate branch for 2.0 milestone stuff or will we use `master` branch for these changes? 
e.g. it is too early to upgrade kotlin to 1.6 on `master` ? :)

**Comment by sksamuel** [comment]
Let's upgrade master to 1.6

**Comment by yogurtearl** [comment]
Updated this PR to upgrade kotlin to 1.6.10: https://github.com/sksamuel/hoplite/pull/267
