### ISSUE TITLE
data class with multiple constructors and single param value constructor won't select appropriate constructor

### ISSUE THREAD

**Issue by alexis-airwallex** [sksamuel/hoplite#230]
when have a data class that normally accepts just a single value param but allows for overriding default behavior with additional parameters will only select the first constructor to try and instantiate the data class.  I will raise a PR against this issue to loop through all available data class constructors in an attempt to find one that matches the MapNode defined params and values and instantiate the class from a selection of constructors.

**Comment by alexis-airwallex** [comment]
Ah cool thx have forked and raised the PR.
https://github.com/sksamuel/hoplite/pull/231

**Comment by sksamuel** [comment]
This was released in 1.4.11.

**Comment by alexis-airwallex** [comment]
Cool thx for a great library👍👍
