### ISSUE TITLE
AWS Parameter Store get-parameters-by-path support

### ISSUE THREAD

**Issue by chrsblck** [sksamuel/hoplite#232]
AWS Parameter Store allows you to query for all params by a path prefix. As an example, here's the `aws-cli` usage:

```
aws ssm get-parameters-by-path --recursive --path /test --with-decryption
```

It would be nice if hoplite supported this. I'm not sure if it should be passed into the `ParameterStorePreprocessor` or decoratively via yaml (application.yml). Ideally, the user would be able to choose the path-prefix dynamically. E.g., choosing the path by `ENV_NAME` of the running app. `/$env/$appName`

For reference, Spring Boot's [`cloud config`](https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.0.0.RELEASE/multi/multi__cloud_environment.html#_integrating_your_spring_cloud_application_with_the_aws_parameter_store) has this functionality as well.

**Comment by sksamuel** [comment]
I've added `ParameterStorePathPreprocessor` to support this, but it's hard to test without an actual instance. Can you try the latest snapshot ?

**Comment by chrsblck** [comment]
Thanks @sksamuel!

I've given it a try and isn't working as I would expect. Looking at the source code, it appears that I would still need to configure each `key:value` in the yaml. I was thinking this aws path processor would be similar to the environment-processor, meaning it would apply matches to `MyConfig.kt`, not necessarily what is in the yaml file.

**Comment by sksamuel** [comment]
Ahh I see.

**Comment by sksamuel** [comment]
I've added ParameterStorePathPropertySource which is what you need really,
not a preprocessor.

Can you test it? It will use the full name from AWS as the key name - we
can add extra options to tweak that if needed.

**Comment by chrsblck** [comment]
Wow, that was fast. Yes, I'll give it a test shortly and report back.

**Comment by chrsblck** [comment]
Looks better, but still isn't working. I think there needs to be some logic to convert the result map to how hoplite can process.

E.g., response in `ParameterStorePathPropertySource.node`:
```
map = {
  /test/my-app/db/username=StringNode(value="username", ...)
}
```

I would  suspect we  need to  remove the prefix in this mapping above, something like

```Kotlin
override fun node(context: PropertySourceContext): ConfigResult<Node> {
  return fetchParameterStoreValues().map { params ->
    val map = params.associate { param -> param.name.removePrefix(path) to StringNode(param.value, Pos.NoPos) }
```

That  way the map returned would match the config structure of

```
map = { /db/username=StringNode(...) }
```

**Comment by sksamuel** [comment]
And in this example, do you want /test/my-app/db/username to map to
test.my-app.db.username in the hoplite tree ?

**Comment by chrsblck** [comment]
No, it would map to `db.username`. This is  because we have env specific paths for apps and/or shared resources

```
/test/svc1/db/username=...
/test/svc2/db/username=...
/test/shared/kafka/bootstrap-server=...
/prod/svc1/db/username=...
...
```

And just for clarity, the yml file would be something like

```
db:
  username: postgres
kafka:
  bootstrap-server: localhost:9092
```

**Comment by sksamuel** [comment]
Ok, so you want to strip prefix and then dot expand.
Easy enough.

**Comment by sksamuel** [comment]
Ok thats done @chrsblck

**Comment by chrsblck** [comment]
@sksamuel Looks right, I see the MapNode contains the ssm params, but it's not applied. Meaning, the `loadConfigOrThrow<MyConfig>()` throws with "missing params" for everything in ssm

**Comment by sksamuel** [comment]
Did you add it to the config loader ?

**Comment by chrsblck** [comment]
@sksamuel yeah, see my updated comment. I updated/edited my last comment

**Comment by sksamuel** [comment]
The leading / might be breaking it, try snapshot 64 in a couple of mins when it's built.
It's annoying I don't have an SSM to test this against, but I think this might be the last issue.

**Comment by chrsblck** [comment]
> It's annoying I don't have an SSM to test this against, but I think this might be the last issue.
Yeah, I bet. I really appreciate the work! And I'm happy to test it :)

**Comment by chrsblck** [comment]
@sksamuel yep, that was it! It's working :tada: :partying_face:

**Comment by sksamuel** [comment]
Ok I'll release this.

**Comment by chrsblck** [comment]
Where's the "buy me a beer" donation button on this project?!?

**Comment by sksamuel** [comment]
It's buy me a gevrey chambertin button.

**Comment by sksamuel** [comment]
1.4.12 released.

**Comment by chrsblck** [comment]
@sksamuel thank you!

**Comment by sksamuel** [comment]
You're welcome.
