### ISSUE TITLE
1.4.10 breaks loading configs from paths

### ISSUE THREAD

**Issue by jenssuhr** [sksamuel/hoplite#234]
Replacing `Try` with `Result` unfortunately broke `ConfigSouce::fromPath` (and maybe other functions as well). `Try`'s `fold` takes the left/error case as its first argument, but for `Result`'s `fold` the first parameter is the success case. This causes the function to always return a `ConfigFailure` if the given path is actually valid. 

1.4.9:
```kotlin
Try { Files.newInputStream(path) }.fold(
  { ConfigFailure.UnknownSource(path.toString()).invalid() },
  { PathSource(path).valid() }
)
```

1.4.10:
```kotlin
runCatching { Files.newInputStream(path) }.fold(
  { ConfigFailure.UnknownSource(path.toString()).invalid() },
  { PathSource(path).valid() }
)
```

**Comment by sksamuel** [comment]
Thanks for spotting this. 1.4.13 released with fix.
