### ISSUE TITLE
LocalTimeDecoder is missing from 1.4.13

### ISSUE THREAD

**Issue by brezinajn** [sksamuel/hoplite#235]
Probably a build issue?

**Comment by sksamuel** [comment]
Ahh I see, you added it to the date-time module, not the core module.
The date-time module is for kotlinx date time, but you wanted the JDK LocalTime.
I can move it.

**Comment by sksamuel** [comment]
Try 1.4.14

**Comment by brezinajn** [comment]
Sorry my bad. Thanks for clarification.
