### ISSUE TITLE
Making hoplite work for POJOs

### ISSUE THREAD

**Issue by aucampia** [sksamuel/hoplite#239]
Currently there is nothing like hoplite for java, the closest that existed was cfg4j but this is now derelict. Would you be open to adding support for Java POJOs to hoplite? I would be happy to work on adding this feature if you are interested.

**Comment by sksamuel** [comment]
I guess it could make sense for Java records ?

The beauty of this approach for Kotlin is that the config classes are
concise. The implementation would still also need the kotlin std lib and
reflection libraries on the classpath.
