### ISSUE TITLE
Inline value class fails to decode into nullable property

### ISSUE THREAD

**Issue by Kantis** [sksamuel/hoplite#241]
example: https://github.com/sksamuel/hoplite/pull/240

**Comment by sksamuel** [comment]
@Kantis this still an issue ?

**Comment by sksamuel** [comment]
Looks like a bug with Kotlin itself.
I've raised this https://youtrack.jetbrains.com/issue/KT-51659

**Comment by Kantis** [comment]
Ah, cool :) nice find!

**Comment by Kantis** [comment]
Re-opened since it's still an issue. I suppose it'll be hard to fix before the Kotlin bug is fixed though.

**Comment by Kantis** [comment]
Fixed in Kotlin 1.7 I think

**Comment by sksamuel** [comment]
Fixed if you upgrade kotlin to 1.7
