### ISSUE TITLE
Ensuring Order Specific Properties

### ISSUE THREAD

**Issue by ultraviolet-jordan** [sksamuel/hoplite#244]
Hey,

I am using your library for loading Toml files.
Here is an example Toml file.

```
opcode = 101
[block]
    "experience" = "IntV1"
    "skillId" = "Byte"
    "level" = "ByteC"
```

And now loading it.
```
    data class TomlFile(
        val opcode: Int,
        val block: Map<String, String>
    )
```

```
val file = ConfigLoader().loadConfigOrThrow<TomlFile>("/testfile.toml")
```

The problem I am having is **_file.block_** is not ensured to be the same ordering as defined in the Toml file. For example **_file.block_** can return 
```
skillId to Byte
level to ByteC
experience to IntV1
```

instead of 
```
experience to IntV1
skillId to Byte
level to ByteC
```

Is this something not accounted for or is there something I can do to ensure the same order as defined in the Toml file?
Thanks.

**Comment by sksamuel** [comment]
Hoplite shouldn't care about the order. Are you seeing this fail if you try
it ?

**Comment by ultraviolet-jordan** [comment]
Thanks I was able to resolve it.
