### ISSUE TITLE
Read json from aws secrets manager

### ISSUE THREAD

**Issue by bonsmik** [sksamuel/hoplite#250]
I have couple of issues/suggestions

**I have secrets in aws as key value pairs so when reading secret I receive value in json format like this**

```
{ "secret": "very-secret-value-in-secrets-manager"}
```

 I tried following but it didn't work

My config:
```
data class Auth(val secret: Masked)
data class Config(val app: App, val database: DatabaseConfig, val auth: Auth)
```
yaml
```
auth: ${awssecret:arn:xyz}
```

To make it work I tweaked preprosessor a bit:

```
    override fun handle(node: PrimitiveNode): Node = when (node) {
        is StringNode -> {
            when (val match = regex.matchEntire(node.value)) {
                null -> node
                else -> {
                    val key = match.groupValues[1]
                    val value = fetchValue(key)
                        .getOrElse { throw ConfigException("Failed loading secrets value from key '$key'", it) }
                    try {
                        JsonParser().load(value.byteInputStream(), "") // try to parse json values
                    } catch (e: UnsupportedOperationException) {
                        node.copy(value = value)
                    }
                }
            }
        }
        else -> node
    }
```

Not sure if this is the way it could work or is there a better way to achieve this. Any suggestions?

**Preprocessing multiple times**

Maybe this another thing would need a another question but I write it here anyway as it somehow is related above. 
My setup have multiple aws environments i.e. multiple secret ids to retrieve secrets. My deployment process creates secrets so I don't know the secretIds before deployment.

in my yaml i would use environment variable:
```
database: ${DBSECRET}
```

After first round this would evaluate:
```
database: ${awssecret:arn:db-secret-id}
```

And eventually after processing like above this would end up like this
```
database:
  user: db-user
  pass: db-pass
  url: db-url
```

Not sure how this could be implemented with current code and not sure if this is feasible idea at all. 

Thanks for the cool lib though :)

**Comment by sksamuel** [comment]
So I've thought about this, and perhaps one option is that we add an AWSSecretsManagerPropertySource which brings in the json node and uses it like any other property source, perhaps with a prefix to narrow down to a subtree.

**Comment by sksamuel** [comment]
> Maybe this another thing would need a another question but I write it here anyway as it somehow is related above. My setup have multiple aws environments i.e. multiple secret ids to retrieve secrets. My deployment process creates secrets so I don't know the secretIds before deployment.
> 
> in my yaml i would use environment variable:
> 
> ```
> database: ${DBSECRET}
> ```
> 
> After first round this would evaluate:
> 
> ```
> database: ${awssecret:arn:db-secret-id}
> ```
> 
> And eventually after processing like above this would end up like this
> 
> ```
> database:
>   user: db-user
>   pass: db-pass
>   url: db-url
> ```
> 
> Not sure how this could be implemented with current code and not sure if this is feasible idea at all.
> 
> Thanks for the cool lib though :)

If you use an env inside the aws string it should work, as it will resolve the env var first.

`database: awssm://${DBSECRET}`
