### ISSUE TITLE
Empty or missing config fails even if config class has defaults

### ISSUE THREAD

**Issue by chris-ryan-square** [sksamuel/hoplite#291]
This is with version 2.0.2

This test should pass, with the config returned the default MyConfig().

```
import com.sksamuel.hoplite.ConfigLoader
import io.kotest.core.spec.style.FreeSpec

class FooTest : FreeSpec({
  "x" {
    val config = ConfigLoader().loadConfigOrThrow<MyConfig>()
    println("My config is: $config")
  }
})

data class MyConfig(
  val name: String = "",
  val nested: NestedConfig = NestedConfig(),
)

data class NestedConfig(
  val nums: List<Int> = emptyList(),
)
```

It fails with:

> 
> Error loading config because:
> 
>     Missing from config
> com.sksamuel.hoplite.ConfigException: Error loading config because:
> 
>     Missing from config
> 	at app//com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:147)
> 	at app//com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:144)
> 	at app//com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:93)
> 	at app//com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:144)
> 	at app//com.squareup.cash.lease.FooTest$1$1.invokeSuspend(FooTest.kt:34)
> 	at app//com.squareup.cash.lease.FooTest$1$1.invoke(FooTest.kt)
> 	at app//com.squareup.cash.lease.FooTest$1$1.invoke(FooTest.kt)
>

**Comment by chris-ryan-square** [comment]
I took some of the code from the Main.kt in the example-native module. This also needs updating to work with 2.0.2

**Comment by chris-ryan-square** [comment]
This also fails if you supply config sources that are missing.  In 1.14.x this used to work and return the default config.

**Comment by sksamuel** [comment]
@chris-ryan-square ok taking a look

**Comment by sksamuel** [comment]
Ok I see the issue. You have no config at all - no system props, no user settings, no sources. So the entire node tree is undefined.
Previously, env vars were always included so you had _something_ and thus it would proceed to creating the data classes using defaults.
I think it makes sense to throw an error saying you have no config?

**Comment by chris-ryan-square** [comment]
If so, please make it something meaningful for the error that I can deal with.  Since what I need to do is go back to previous behaviour, i.e. give me the default config if there's nothing loaded.

Note that missing config files also triggers this.  So, try the above test with a file that doesn't exist. Our setup is usually 2 config files (both optional), with the current environment file overriding a default file.

**Comment by sksamuel** [comment]
The error would be something like "you don't have any property sources defined".
And how about an option like "ignore empty property sources" ?

**Comment by sksamuel** [comment]
The reason for the change (and bump to 2.0) is to make strict work properly.

**Comment by chris-ryan-square** [comment]
Yes to both the error and the option.

I don't mind the change, I just need to detect and deal with it.

**Comment by sksamuel** [comment]
https://github.com/sksamuel/hoplite/pull/292

**Comment by sksamuel** [comment]
https://github.com/sksamuel/hoplite/pull/292

**Comment by sksamuel** [comment]
Releasing 2.0.3 with allowEmptyTree() to allow your example to work.

**Comment by chris-ryan-square** [comment]
This works perfectly - thanks!
