### ISSUE TITLE
Optionally make using an unresolved substitution value not an error again

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#296]
Before [Hoplite 2](https://github.com/sksamuel/hoplite/blob/master/changelog.md#breaking-changes), it was not necessarily an error if unset environment variables were being referred to in the configuration. This was convenient, because if (e.g. for testing) only a subset of a (big) configuration was actually used, only the environment variables used by the code path were required to be set. Now, *all* variables need to be set, regardless of whether the respective configuration item is actually accessed at runtime or not.

Can we get an option to revert to the old behavior and allow unresolved variables, accepting late failure at runtime?

**Comment by sksamuel** [comment]
Yes good idea.
