### ISSUE TITLE
Exception message should say "*Un*resolved substitution ..."

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#298]
In here

https://github.com/sksamuel/hoplite/blob/142159606bb2146bc1244ecf7fec87f6e7e616f0/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/ConfigFailure.kt#L99

I believe it should say "*Un*resolved substitution ..."

I'd be fine with filing a PR, but first wanted to double-check that you agree.

**Comment by sksamuel** [comment]
Yes agreed.
