### ISSUE TITLE
Types to add

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/hoplite#30]
Year
YearMonth
java.util.Date
SizeInBytes
SortedSet
SortedMap
Triple
IntRange
CharRange
LongRange

**Comment by fagossa** [comment]
hello @sksamuel , Can I work on some of those decoders?

**Comment by sksamuel** [comment]
Absolutely.

**Comment by sksamuel** [comment]
Do you want me to make an issue per decoder

**Comment by sksamuel** [comment]
I have created issues for each of these, so will close this ticket. Put a comment on any ones you want to do so I know not to duplicate.
