### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Nikhil2508** [sksamuel/hoplite#310]
Trying to install this library in Kotlin gradle project.

Getting below error :

Could not resolve com.sksamuel.hoplite:hoplite-core:2.1.5.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact,

Library version
implementation("com.sksamuel.hoplite:hoplite-core:2.1.5")
implementation("com.sksamuel.hoplite:hoplite-json:2.1.5")

**Comment by sksamuel** [comment]
You can see hoplite core in maven search.
https://search.maven.org/search?q=hoplite-core

Sounds like your gradle build isn't setup right. Is it public ?

**Comment by sksamuel** [comment]
Closing as no reply, and sounds like a gradle setup issue.
If you are still having issues reopen.
