### ISSUE TITLE
Kotlinx serialization @SerialName mapper

### ISSUE THREAD

**Issue by vie10** [sksamuel/hoplite#311]
As far, as the Kotlinx Serialization uses code generation, and creates a new constructor for its purposes, it seems to be not possible to map the @SerialName value of param because hoplite references to params, not properties.

Wondering how to resolve it

**Comment by sksamuel** [comment]
Do you have a code example ?

**Comment by vie10** [comment]
Ya, I've create an example project with a test case for this.
Look at https://github.com/vie10/hoplite-ktx-serialization

**Comment by sksamuel** [comment]
I don't know a lot about kotlinx serialization. Are you trying to use the @SerialName annotation (?) as the name to look for in config ?

**Comment by vie10** [comment]
I can explain why doesn't it work in a few examples. Let's take a look to the Bytecode (decompiled).

```java
      public Config(@NotNull String myProperty) {
         Intrinsics.checkNotNullParameter(myProperty, "myProperty");
         super();
         this.myProperty = myProperty;
      }
```
it's what Hoplite works with.

and that's how KotlinX.serialization stores the comment
```java
      @SerialName("my-property")
      public static void getMyProperty$annotations() {
      }
```

and

```java
      public Config(int seen1, @SerialName("my-property") String myProperty, SerializationConstructorMarker serializationConstructorMarker) {
         if (1 != (1 & seen1)) {
            PluginExceptionsKt.throwMissingFieldException(seen1, 1, ((KSerializer)SerialNameMapperTest.Config.$serializer.INSTANCE).getDescriptor());
         }

         super();
         this.myProperty = myProperty;
      }
```

**Comment by vie10** [comment]
Maybe can I access the holder class of param in the param mapper somehow?

**Comment by sksamuel** [comment]
Take a look at https://github.com/sksamuel/hoplite/pull/315
Adjusting parameter mapper contract.

**Comment by vie10** [comment]
Yes, exactly what's needed, thanks!

**Comment by sksamuel** [comment]
Will be in 2.2.0
