### ISSUE TITLE
Collection element decode failure with version 1.4.16 in sealed class

### ISSUE THREAD

**Issue by vasanthdharmaraj** [sksamuel/hoplite#313]
We are using hoplite to parse the Gradle's [libs.versions.toml](https://docs.gradle.org/current/userguide/dependency_management.html#sub:conventional-dependencies-toml) file. The version in the file can be defined in a couple of ways:
```
commons_beanutils = "1.9.4"
commons_codec = { strictly = "1.15" }
```

We had a sealed classes for this as:
```
  sealed class Version {
        abstract val value: String

        data class StrictlyVersion(val strictly: String) : Version() {
            override val value: String
                get() = strictly
        }

        data class ValueVersion(override val value: String) : Version()
    }
```

This was working fine till version `1.4.15` but fails in version `1.4.16` and up.

The error is 
```
Collection element decode failure (:1:5)
Could not find appropriate subclass of class VersionCatalog$Version: Tried VersionCatalog$Version$StrictlyVersion, VersionCatalog$Version$ValueVersion (:6:5)
```

From the release notes I see that this could be because of this change: https://github.com/sksamuel/hoplite/pull/246

**Comment by sksamuel** [comment]
Can you try 2.1.5 ?

**Comment by vasanthdharmaraj** [comment]
Yes, it fails with `2.1.5` too. Here is a PR with a test case showing this failure: https://github.com/sksamuel/hoplite/pull/316. 

And here is a branch in my fork based on the `1.4.15` release where the same test passes: https://github.com/vasanthdharmaraj/hoplite/tree/branch_v1.4.15_sealedclass_test

**Comment by sksamuel** [comment]
2.2.0 is released

**Comment by vasanthdharmaraj** [comment]
Thanks a lot for the quick turnaround on this. Really appreciate it.

**Comment by sksamuel** [comment]
You're welcome
