### ISSUE TITLE
LinkedHashMap does not preserve order when using a sealed interface type as value

### ISSUE THREAD

**Issue by bs-ondem** [sksamuel/hoplite#314]
I encountered a problem with the order of the entries of a `LinkedHashMap` with a sealed interface value type. I simplified the model for the issue.
```
data class Configuration(val expressions: LinkedHashMap<String, Expr>? = null)

sealed interface Expr

data class Const(val number: Int) : Expr
data class Text(val str: String) : Expr
```

When I'm loading a configuration as the following
```
{
    expressions {
        const1 { number = 2 }
        
        const2 { number = 10 }
        
        text1 { str = "This is a example text." }
        
        const3 { number = 42 }
    }
}
```
and checking the order of the keys, it's not like described in the configuration file (`[const1, const3, const2, text1]`).

Is this behavior intentional? I assumed that when using a `LinkedHashMap` the order of the entries should be the same as described in the configuration file.

Edit: I'm using version `2.1.5`.

**Comment by sksamuel** [comment]
I've added a test and it seems to work: https://github.com/sksamuel/hoplite/commit/13ea33eca3101be4324249bd3ed62ac25a6908a1

**Comment by sksamuel** [comment]
Same for Hocon https://github.com/sksamuel/hoplite/commit/366044f411bd627c6b0510f550d53ee831a8b158

**Comment by bs-ondem** [comment]
Thanks for adding the tests, but when you test the values of the map, it fails.
```
    test("linked map of sealed interface should preserve order from hocon") {
      val config = ConfigLoaderBuilder.default()
        .addPropertySource(PropertySource.resource("/sealed_class_linked_hash_map.conf"))
        .build()
        .loadConfigOrThrow<Configuration>().expressions!!

      val expectedExpressions = linkedMapOf(
        "const1" to Const(number = 2),
        "const2" to Const(number = 10),
        "text1" to Text(str = "This is a example text."),
        "const3" to Const(number = 42)
      )
      
      // Passes
      config shouldBe expectedExpressions
      // Passes
      config.keys shouldBe expectedExpressions.keys
      // Fails
      config.values shouldBe expectedExpressions.values

      /*
      Output:
                const1=Const(number=2)
                const3=Const(number=42)
                const2=Const(number=10)
                text1=Text(str=This is a example text.)
       */
      config.forEach { println(it) }
      
      /*
      Output:
                const1=Const(number=2)
                const2=Const(number=10)
                text1=Text(str=This is a example text.)
                const3=Const(number=42)
       */
      expectedExpressions.forEach { println(it) }
    }
```
Even, when you just print the entries of the maps, you can see that they differ from each other. I would expect that when using `LinkedHashMap`s, the order should be preserved when iterating over it.

**Comment by sksamuel** [comment]
I think you would need to not use hocon, but json or yaml.
The hocon parser seems to ignore ordering.

![image](https://user-images.githubusercontent.com/743706/177662375-be6e14be-d2fc-4b00-b448-e4982dd68e64.png)

**Comment by bs-ondem** [comment]
Okay, the `Config` object returning from the [lightbend/config](https://github.com/lightbend/config) destroys the order of the entries and not the `HoconParser`. Nevertheless, I still think the order should remain, especially when using `LinkedHashMap`s. Or what do you think?

But this should be fixed in the [lightbend/config](https://github.com/lightbend/config) project and here.

**Comment by sksamuel** [comment]
Yes it should probably maintain the order and the fix would need to be in
the light bend project.

**Comment by sksamuel** [comment]
Closing this ticket as this is an issue with lightbend.

**Comment by mnonnenmacher** [comment]
For reference, the discussion about preserving configuration order in lightbend config is going on for a long time, unfortunately it does not look like it would be resolved anytime soon:
https://github.com/lightbend/config/issues/733
https://github.com/lightbend/config/issues/365

**Comment by sksamuel** [comment]
I would just ditch hocon for json or yaml.
