### ISSUE TITLE
[Feature] Add json5 format

### ISSUE THREAD

**Issue by AmibeSkyfy16** [sksamuel/hoplite#326]
I'm looking for a way to configure with json5, I did a lot of research, but all I found was this: https://github.com/adamko-dev/json5-kotlin

**Comment by sksamuel** [comment]
We'd need a JVM Json5 library, the other one I found was https://github.com/brimworks/json5.java but that appears dead.

We could support adjusting the jackson library, https://stackoverflow.com/questions/68312227/can-the-jackson-parser-be-used-to-parse-json5

**Comment by AmibeSkyfy16** [comment]
ok interesting, i also find this one : https://github.com/marhali/json5-java its recent

**Comment by sksamuel** [comment]
Looks promising. Probably a bit new for this project to rely on it.
Very easy to add your own parsers though, just a copy n paste of the
existing json one.
