### ISSUE TITLE
Mark `fp` package stuff as internal

### ISSUE THREAD

**Issue by Kantis** [sksamuel/hoplite#332]
Currently the stuff in the fp package leaks onto users classpath when using Hoplite. Was it intentionally put as public api?

I'm using Hoplite and Arrow together sometimes, and it forces me to pick the right import when trying to add `Validated` for instance.

**Comment by sksamuel** [comment]
I'm not sure it can go to internal because it's needed by all the modules, but we could move it into a package name that includes internal so it's clear not to use it ?

Or I can rename it

**Comment by Kantis** [comment]
One way around that could be to create a separate module for "hoplite-internals" and depend on that from the modules using it. 

E.g.:

`hoplite-aws` -> `hoplite-core`
`hoplite-aws` -> `hoplite-internals`
`hoplite-core` -> `hoplite-internals`

( `lhs -> rhs` in this context means a gradle `implementation()` dependency on `rhs` from `lhs`)


This would make the fp stuff invisible to users

**Comment by sksamuel** [comment]
Ah good call, like we do in Kotest.
