### ISSUE TITLE
AWSSM: Introduce syntax to index AWS Secrets manager 

### ISSUE THREAD

**Issue by Kantis** [sksamuel/hoplite#333]
It's possible to store a `Map<String, String>` in AWSSM. Using `awssm://secret[index]` could perhaps be used to fetch the secret by secret id and then fetch `index` from the map?  The index usage would imply that secret is of Map-type

**Comment by sksamuel** [comment]
Yeah I like that.

**Comment by sksamuel** [comment]
What's the AWS code to get a map from the secret value? Eg map version of this:

```
      val valueRequest = GetSecretValueRequest.builder().secretId(key).build()
      val valueResponse = client.getSecretValue(valueRequest)
      val value = valueResponse.secretString()
```

**Comment by Kantis** [comment]
It's not typed in the AWS SDK, as far as I know. What I've done is to parse the map using kotlinx-serialization:

```kotlin
   fun getCredentialMap(key: String): Map<String, String> {
      val result = client.getSecretValue(reqBuilder.secretId(key).build()).secretString()
      return decodeMap(result)
   }

   fun decodeMap(@Language("json") raw: String): Map<String, String> {
      return Json.Default.decodeFromString(raw)
   }
```

**Comment by sksamuel** [comment]
Is this a good idea? What if you want to rotate a key? You have to update the entire json object with the new value embedded?

**Comment by Kantis** [comment]
Normally I use the web interface for handling AWSSM, which lets you alter specific keys in the map quite easily.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/316857/184590383-5bca31f0-81d7-4fbd-8d0d-7e0e59187d0f.png">

What do you think?

**Comment by sksamuel** [comment]
Yeah I guess that works. But it's quite manual. I like to populate keys directly from terraform.

**Comment by Kantis** [comment]
Ok :) I typically use it for keys I get from clients and have no power to rotate them after the fact. So I typically put them in AWSSM like that. Anyway, if you're unsure we can close this.

**Comment by sksamuel** [comment]
I think if the AWS client did it, it would be fine, but we'd have to bring in the json library for this?
