### ISSUE TITLE
Support reading configuration files from dependencies in the classpath

### ISSUE THREAD

**Issue by incendium** [sksamuel/hoplite#344]
It would be nice if there was a way to read configuration files from JAR files on the classpath.  This mainly comes in handy for HOCON integration, in which the default HOCON configuration loader will load the local `application.conf` file as well as any `reference.conf` files found in any JAR files on the classpath and merge them all together.

I can kind of get around this by defining a custom `PropertySource` which directly accepts a pre-constructed HOCON `Config` object, but I am not sure if this is the correct or desired way to do this.

**Comment by sksamuel** [comment]
You should be able to reference anything on the classpath by just using the resource property source.
It won't look for duplicates though, it'll just take the first match.

**Comment by incendium** [comment]
That's the problem then, as HOCON will look for all files with the names `application.conf`, `application.json`, `application.properties`, and `reference.conf`.  If I wanted to use a `PropertySource` to handle this then, are there any pitfalls I should be aware about?  This is what I threw together during testing:

```kotlin
class HoconConfigPropertySource(
    private val config: Config = ConfigFactory.load(),
    private val dotPath: DotPath = DotPath.root,
) : PropertySource {
    private val source = "Pre-resolved HOCON object"
    override fun source(): String = source

    override fun node(context: PropertySourceContext): ConfigResult<Node> {
        return MapProduction(config.root(), config.origin(), source, dotPath).valid()
    }
}
```

**Comment by sksamuel** [comment]
You could write a property source that pulls all those from the classpath, and passes each one through the hocon parser, or create the hocon object in advance like in your snippet above. The only disadvantage I can think of with the latter is that hocon will do all it's resolution first, before hoplite gets involved, which may or may not result in edge cases (can't think of anything off top of my head though).

**Comment by incendium** [comment]
Thanks for the feedback and quick replies!  I'm mainly looking for the latter, as I am primarily looking for a more maintained replacement for config4k.  That said, I'll play around with the first as well to see if that offers any advantages.  Appreciate the help!

**Comment by sksamuel** [comment]
I wouldn't be against adding this into Hoplite itself. Then you can have the same magic but with yaml or toml.
We could have a flag on resource sources to indicate if you want to load all of them or another property type that does it.
