### ISSUE TITLE
Configuration file cannot be found in Graalvm native image

### ISSUE THREAD

**Issue by sergio11** [sksamuel/hoplite#349]
Hi, 

Thanks for this great library,

I'm integrating it into my Ktor project which will run as a native Graalvm image.

I'm using theses dependencies:

```
implementation("com.sksamuel.hoplite:hoplite-core:$hoplite_core_version")
implementation("com.sksamuel.hoplite:hoplite-yaml:$hoplite_core_version")
```

I have the following application.yml

![image](https://user-images.githubusercontent.com/6996211/197393916-cc939d0e-37ff-4540-ad76-248e34690dbe.png)

I have integrated the following configuration in order to make the yml files available in the binary

```
  buildArgs.add("-H:+ReportExceptionStackTraces")
  buildArgs.add("-H:IncludeResources='.*(yml|xml)$'")
  buildArgs.add("-H:Log=registerResource:5")
  imageName.set("mfa_graalvm_service")
```

At the time of starting the microservice and instantiating the configuration Koin module, the application crashes because it cannot find the application.yml file

```
val configModule = module {
    single<AppConfig> {
        ConfigLoaderBuilder.default()
            .addResourceSource("/application.yml")
            .strict()
            .build()
            .loadConfigOrThrow()
    }
    single { get<AppConfig>().mfa }
    single { get<AppConfig>().redis }
    single { get<AppConfig>().auth }
}
```

Could you tell me if I have to apply any additional configuration so that the library finds the configuration file?

Thank so much, Greetings

**Comment by sksamuel** [comment]
addResource uses the JVM based class loader. Does this still work with Graal ?
