### ISSUE TITLE
CascadeMode.Override doesn't work

### ISSUE THREAD

**Issue by TheBestPessimist** [sksamuel/hoplite#350]
Hello,

Override doesn't seem to work, instead hoplite loads the first value and keeps that.

Sample project here: https://github.com/TheBestPessimist/sksamuel-hoplite-issues-350-hoplite-cascade-override-bug/blob/master/src/test/kotlin/aaaa/Test.kt.

Just run `gradle test`

**Comment by sksamuel** [comment]
The fallback files should be last, not first.
If this isn't clear in the docs please point me to the spot and I will update them.
Thanks!

**Comment by TheBestPessimist** [comment]
When i read `Override` it leads me to think of the following:
if a property has a value in multiple files, then the value from "current file" will be replaced whenever the same property with an existing value is found in the "next file". Override = replace existing value with new one.

so for example
with the following file structure

- file1: 
	- prop1 = f1.1
	- prop2 = <empty>
- file2:
	- prop2 = f2.2
	- prop3 = f2.3
- file3:
	- prop2 = <empty>
	- prop3 = f3.3

i will have the following properties after the Override mode:
```kotlin
    val config: Config = ConfigLoader.builder()
        .addResourceOrFileSource("file1") // this one is the base config
        .addResourceOrFileSource("file2") // this one overrides whatever was set above
        .addResourceOrFileSource("file3") // this one overrides whatever was set above
        .withCascadeMode(CascadeMode.Override)
        .build()
        .loadConfigOrThrow()
```
- prop1 = f1.1
- prop2 = f2.2
- prop3 = f3.3

----

Regarding documentation, 

For `CascadeMode` there is no KDoc for any of the 3 enum entries (maybe because it's experimental?).

In the readme, if i search for `cascad` i have 4 hits but none mention the `Override` mode: 
![image](https://user-images.githubusercontent.com/4482210/204730362-afb971f3-7a8b-4404-bedc-6d8114d5dbb0.png)
and
![image](https://user-images.githubusercontent.com/4482210/204730435-34b9a9f3-9471-48e0-b054-2f54effa1aa2.png)

If i search in readme for `overrid`, there are 11 hits, and only the first one barely hints to the `CascadeMode.Override`: 
![image](https://user-images.githubusercontent.com/4482210/204730714-40ccc481-a371-4d37-b5a1-24ce0a45f3be.png)

----

My logic however came from the following: in the [Cascading Config](https://github.com/sksamuel/hoplite#cascading-config) section it is explained that the "default?" cascading mode is "take first occurrence".

So if i were to use
```kotlin
ConfigLoader()
	 .withCascadeMode(CascadeMode.Override)
	.loadConfigOrThrow<Config>("/application-prod.yaml", "/application.yaml")
```
this would mean that the _more specific_ prod configs would be overridden by the _less specific_ default configs, which is obviously not what i want.
=> It made sense that the order of the files is "from general to specific".

**Comment by sksamuel** [comment]
It's the other way around. The files don't override each other, but "fallthrough". So if a value is not present in an earlier file, then it looks into the second file and so on.

So you just need to reverse the order of your files. I will look to clarify the docs.

**Comment by TheBestPessimist** [comment]
In that case, maybe `override` should be replaced with `fallthrough`?
Anyway, i also expected override to work like that because that's how spring does it too.

**Comment by sksamuel** [comment]
That's a good suggestion. I'll rename and deprecate the old name.
