### ISSUE TITLE
Overriding values of a sealed class with `EnvironmentVariablesPropertySource` is always case-sensitive

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#353]
I'm using `ConfigLoaderBuilder.addEnvironmentSource()` which defaults to `allowUppercaseNames: Boolean = true` (side remark, that property should probably just be named `ignoreNameCase`).

However, I realized that overriding a property from a sealed class via an upper-cased environment variable name does not work. It seems that the sealed class name is being looked for in its exact casing as part of the environment variable name.

For example, in [this test](https://github.com/oss-review-toolkit/ort/pull/6226/files#diff-d93772e3eb02975f7e3c04e20df02f203a8b3626fcfd63a877406001a87f7df5R263) `postgresStorage` is a sealed class and I can override a property with `ort.scanner.provenanceStorage.postgresStorage.connection.password`, but if I change the "path" e.g. to `ORT.scanner.provenanceStorage.postgresStorage.connection.password` it stops working. But the same works if the "path" does not come across a seal class instance, e.g. `ORT.scanner.storages.postgres.connection.password` works to override the password.

**Comment by sksamuel** [comment]
Just done a quick test and it does work. You need to use __ for the separator if you're not using periods.

**Comment by sschuberth** [comment]
Thanks for double checking! Any idea why [this change](https://github.com/oss-review-toolkit/ort/pull/6248/files) fails our environment variable override test then?

**Comment by sksamuel** [comment]
I would imagine the algorithm I'm using to convert upper to match isn't working in the exact way needed for this string. What is the field that ORT__SCANNER__PROVENANCESTORAGE__POSTGRESSTORAGE__CONNECTION__PASSWORD is overriding ?

**Comment by sschuberth** [comment]
You can see the reference configuration YAML file [here](https://github.com/oss-review-toolkit/ort/blob/d30c27fb4dd8468d5c1a6877298ae8649d3d0b08/model/src/main/resources/reference.yml#L238). Data-type wise, the "path" is ort -> [scanner](https://github.com/oss-review-toolkit/ort/blob/d30c27fb4dd8468d5c1a6877298ae8649d3d0b08/model/src/main/kotlin/config/OrtConfiguration.kt#L103) -> [provenanceStorage](https://github.com/oss-review-toolkit/ort/blob/d30c27fb4dd8468d5c1a6877298ae8649d3d0b08/model/src/main/kotlin/config/ScannerConfiguration.kt#L118) -> [postgresStorage](https://github.com/oss-review-toolkit/ort/blob/d30c27fb4dd8468d5c1a6877298ae8649d3d0b08/model/src/main/kotlin/config/ProvenanceStorageConfiguration.kt#L36) -> [connection](https://github.com/oss-review-toolkit/ort/blob/d30c27fb4dd8468d5c1a6877298ae8649d3d0b08/model/src/main/kotlin/config/ScanStorageConfiguration.kt#L78) -> [password](https://github.com/oss-review-toolkit/ort/blob/d30c27fb4dd8468d5c1a6877298ae8649d3d0b08/model/src/main/kotlin/config/PostgresConnection.kt#L46).

**Comment by sschuberth** [comment]
So the `password` field is simply a `String`. I guess the `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)` annotation should not interfere?

**Comment by sksamuel** [comment]
Ok so it converts the key to ort.scanner.provenancestorage.postgresstorage.connection.password 
It doesn't know that PROVENANCESTORAGE should map to provenceStorage.
The way this works is it builds the env map in advance, it doesn't lazily look into the env vars.
I'll see how much work it is to make a lazy source that can do that.

**Comment by sschuberth** [comment]
> It doesn't know that PROVENANCESTORAGE should map to provenceStorage.

Hmm, why not? I currently don't see where / why a lazy evaluation would be required here.

**Comment by sksamuel** [comment]
The tree of values is created first, then the object graph is constructed it looks inside the value tree for matching values.

The env property source converts your upper case string to lower case, replacing __ with a dot. But you don't want lowercase, you want camel case for it to match. And how could the env property source know what the correct camel case should be. It could be proVenceStorAge.

If it was lazy, the env property source could be clever about it and say "you're asking for provenceStorage" let me look for "PROVENCESTORAGE" and the earlier conversation wouldn't even need to happen.

Right now there's no logic in the property sources other than "give me a tree of values".

**Comment by sschuberth** [comment]
> If it was lazy, the env property source could be clever about it and say "you're asking for provenceStorage" let me look for "PROVENCESTORAGE" and the earlier conversation wouldn't even need to happen.

Ah, now I see what you mean about "lazy" here; I thought you're somehow referring to Kotlin's `lazy`. But yes, looking up properties in the environment *on demand* should solve it, and I was actually assuming it was implemented that way. Hence my misguidance regarding the sealed class, sorry for that red herring.
