### ISSUE TITLE
Show the exactly line of (YAML) syntax errors

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#354]
Would it be possible to show the exactly line of syntax errors, for example for YAML files where a string value if set to just `*` (unquoted)?

**Comment by sksamuel** [comment]
Do you have an example input file and a config file that fails ?

**Comment by sschuberth** [comment]
Yes, but it's rather complex. The reason why I'm asking is https://github.com/oss-review-toolkit/ort/issues/6327. My hunch is that Hoplite reports "Could not parse config.yml" because the `POSTGRES_PASSWORD` is evaluated to a string that starts with a `*`, and as it's being used unquoted, the parsing fails as [`*` is interpreted as the start of an alias](https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell#anchors-aliases-and-tags).
