### ISSUE TITLE
Fix exception logging for config loader

### ISSUE THREAD

**Issue by grindr-eric-ha** [sksamuel/hoplite#359]
Log more info when config loader file names (env names) are mismatched
<img width="875" alt="Screenshot 2023-03-06 at 4 09 55 PM" src="https://user-images.githubusercontent.com/101289692/223277887-e51ffe9f-0de9-4e87-a825-d655e3813ee7.png">

**Comment by sksamuel** [comment]
This was fixed in a previous release, so bumping to 2.7.2 should be sufficient.
