### ISSUE TITLE
Fallback syntax with nested env var fails for the primary variable

### ISSUE THREAD

**Issue by shoprunner-sc** [sksamuel/hoplite#364]
If I define it like this:
```yaml
value: ${PRIMARY:-${ssm:/some/ssm}}
```

If PRIMARY env var is defined, for example, 
```
PRIMARY=a
```
then value becomes:
```
value: a}
```
Notice that value gets additional } in the end.

If PRIMARY is NOT defined, then it gets correctly resolved from ssm.
For example, if ssm contains ```b```, and PRIMARY is not defined, then the expression evaluates to
```
value: b
``` 

Also, I observed that nested expression does NOT work if I use just env vars.
For example,
FALLBACK=b
```
value: ${PRIMARY:-${FALLBACK}}
```
Then the app fails with can't resolve ${FALLBACK} error.
This is very inconsistent, because on one hand it **almost** works if fallback is ssm syntax and doesn't work if it is an env var on the other.

**Comment by sksamuel** [comment]
This is dependent on the order in which the preprocessors run.
You could define your own order by instantiating the config loader builder as empty and then adding the preprocessors back in.
But I would just not try to mix n match the syntax.

**Comment by sksamuel** [comment]
You can't use a ${} expression as a fallback no.

Best workaround is

value1: ${PRIMARY}
value2: "awssm:/some/ssm"

Then in code do value1 ?: value2

I'll look to add something later to support your usecase.
