### ISSUE TITLE
nested substitutions

### ISSUE THREAD

**Issue by slushpupie** [sksamuel/hoplite#365]
Should the LookupPreprocessor handle nested substitutions?   The following example does not work, but its not clear from the documentation if it even _should_ work:

```
full = "This contains ${part1}"
part1 = "part1 (${subtext1})"
subtext1 = "some subtext"
```

It produces an error of 
`Unresolved substitution This contains part1 (${subtext1}) at (default.conf:1)`

If nested substitutions should not work, can at least the documentation be updated to clearly reflect that? I would like them to work, if that can be a feature request.

**Comment by sksamuel** [comment]
So in this case you expected full to be "This contains part1 (some subtext)" ?

**Comment by slushpupie** [comment]
Yes, that is what I expected.

**Comment by sksamuel** [comment]
We can make nested subscriptions work but adding it under the current syntax could break existing users code.

I'll add it under new syntax.
