### ISSUE TITLE
Ability to set value to null explicitly 

### ISSUE THREAD

**Issue by ljufa** [sksamuel/hoplite#377]
When using the cascading feature for nullable values, there should be a way to unset (set to null) an already set value. i.e.

```kotlin
data class MyConfig(val username: String?)
...
builder
         .addResourceSource("/local.yaml", optional = true, allowEmpty = true)
         .addResourceSource("/dev.yaml", optional = true, allowEmpty = true)
```

for `dev.yaml`
```yaml
username: something
```

it should be possible to write `local.yaml`
```yaml
username: null 
# or 
username: 
```

**Comment by sksamuel** [comment]
Can you try 2.8.0.RC1 which has this feature if you set null override in the config builder.

**Comment by sksamuel** [comment]
@ljufa did that work ?

**Comment by ljufa** [comment]
Hey @sksamuel, sorry for the late reply.
I just tested it and it seems to be working fine. 
Thank you!

**Comment by sksamuel** [comment]
cool
