### ISSUE TITLE
FileWatcher threads pool prevent app from shutdown

### ISSUE THREAD

**Issue by jakubzieba** [sksamuel/hoplite#387]
Thread pool created in FileWatcher https://github.com/sksamuel/hoplite/blob/master/hoplite-watch/src/main/kotlin/com/sksamuel/hoplite/watch/watchers/file.kt#L30 prevent app from shutdown. Threads in pool should be set as deamon or FileWatcher should have function like stop or destroy.

**Comment by sksamuel** [comment]
Thanks for bug report. I've set the file watcher to use daemon threads for the next release and will release a patch version of 2.7.x
