### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by shorinami** [sksamuel/hoplite#405]
Is there any particular reason to not support java 8?

**Comment by sksamuel** [comment]
Other than its 1000 years old, I suppose not if the project compiles with it :)

**Comment by shorinami** [comment]
> Other than its 1000 years old, I suppose not if the project compiles with it :)

I built it with that without any problems

**Comment by sksamuel** [comment]
If you want to make a PR I'll release 2.8.0 on JDK8

**Comment by shorinami** [comment]
> If you want to make a PR I'll release 2.8.0 on JDK8

That would be great! Is there anything else than changing the target version?
Also noticed, that because of the quite old postgres version in test, it was failing for me because of a wrong timezone, update to latest fixed that

**Comment by sksamuel** [comment]
Ok cool. Yeah should just be a matter of changing the gradle build files, and then the GHA workflows.

**Comment by shorinami** [comment]
> Ok cool. Yeah should just be a matter of changing the gradle build files, and then the GHA workflows.

Done, https://github.com/sksamuel/hoplite/pull/406
Although, did not touch the workflows, explained why in the PR

**Comment by shorinami** [comment]
That is it! Thank you :)
