### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by outlndrr** [sksamuel/hoplite#419]
When is the library planned to be released? Because it has not been updated since August 6, 2023, and at the same time there are new commits in the master branch

**Comment by sksamuel** [comment]
I'll get a release out in the coming weeks of 2.8
and then focus on 3.0

**Comment by glippert** [comment]
I have been holding off announcing an internal release to my team based on new features in version 2.8. By company policy I can't release something that is based on dependencies with RC status. Note that 2.8 RC1 was announced 475 days ago. Can you please clarify, is there a 2.8 release forthcoming or has 2.8 hit a show stopping issue or...?

**Comment by sksamuel** [comment]
2.8.0 RC has been out for a long time, so I figure any show stoppers would have been found by now.
I have been running that version in prod for a year on 500+ nodes.
Anyway, I've released 2.8.0 final now.
Thanks for the patience!
