### ISSUE TITLE
Is 2.8.0 a breaking release?

### ISSUE THREAD

**Issue by staktrace** [sksamuel/hoplite#451]
The 2.8.0 release recently appears to be binary-incompatible with the older 2.7.5 release. Specifically when 2.8.0 is on the runtime classpath and the code was compiled against 2.7.5, we are getting this sort of error:

```
Caused by: java.lang.NoSuchMethodError: 'com.sksamuel.hoplite.fp.Validated com.sksamuel.hoplite.ConfigLoader.loadConfig(kotlin.reflect.KClass, java.util.List, java.util.List, com.sksamuel.hoplite.ClasspathResourceLoader)'
```

Is this intentional? We can probably deal with it if it is, but if it's not intentional I'd rather wait for a 2.8.1 that restores binary compatibility with 2.7.5.

Thanks!

**Comment by staktrace** [comment]
Relatedly, it would be great to have the https://github.com/sksamuel/hoplite/blob/master/changelog.md file updated for 2.8.0 as well.

**Comment by sksamuel** [comment]
I'll do a 2.8.1 that reverts that change, it's internal only.

**Comment by sksamuel** [comment]
2.8.1 is out
