### ISSUE TITLE
Denormalization of map keys does not work correctly when loading from ENV with underscores

### ISSUE THREAD

**Issue by schmist** [sksamuel/hoplite#454]
Loading a map key value pair (`map__foo=bar`) from ENV leads to a map key `map__foo` instead of `foo`. This used to work correctly for 2.7.x and is probably broken since 2.8.x.

The problem seems to be in the node denormalization method: `(v.sourceKey ?: k).removePrefix("$sourceKey.")`.
Either `v.sourceKey` needs to be transformed to `map.foo` before (when constructing the node) or the `$sourceKey.` prefix has to be adapted for source keys with underscores.

**Comment by rocketraman** [comment]
@schmist Can you verify the linked PR solves the issue for you?

**Comment by schmist** [comment]
@rocketraman Yep, I guess this will work. Thanks.
