### ISSUE TITLE
`@ConfigAlias` has no effect on YAML in version 2.8.2

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/hoplite#455]
I have this [class](https://github.com/oss-review-toolkit/ort/pull/9325/commits/e12795357f324ec0a443fa15e6eaa3427e9cf325):

```
data class LicenseFilePatterns(
    val licenseFilenames: Set<String>,
    val patentFilenames: Set<String>,
    @ConfigAlias("rootLicenseFilenames")
    val otherLicenseFilenames: Set<String>
)
```

which gets deserialized from YAML:

```
licenseFilePatterns:
  licenseFilenames: ['license*']
  patentFilenames: ['patents']
  rootLicenseFilenames: ['readme*']
```

which fails in version 2.8.2 with

```
Failed to load ORT configuration: - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfigurationWrapper' because:
    - 'ort': - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfiguration' because:
        - 'licenseFilePatterns': - Could not instantiate 'org.ossreviewtoolkit.model.config.LicenseFilePatterns' because:
            - 'otherLicenseFilenames': Missing class kotlin.collections.Set from config
```

Reverting to version 2.7.5 solves the issue.

**Comment by rocketraman** [comment]
@sschuberth @laurentthiebaudezm  Can you verify the linked PR solves the issue for you?

**Comment by laurentthiebaudezm** [comment]
> @sschuberth @laurentthiebaudezm Can you verify the linked PR solves the issue for you?

It doesn't work for me, still have those "com.sksamuel.hoplite.ConfigException:  Error loading config because:\n\n    - Could not instantiate ... Missing String from confi"

**Comment by sschuberth** [comment]
Can it be something YAML-specific? Otherwise I would have expected the existing tests in `hoplite-toml/src/test/kotlin/com/sksamuel/hoplite/toml/ConfigAliasTest.kt` to already catch the issue. Maybe adding a test that loads `.yaml` instead of `.toml` would reveal the issue?

**Comment by laurentthiebaudezm** [comment]
Actually we don't use yaml, as I said we use environment variables:

```
ConfigLoaderBuilder.default()
            .addSource(
                EnvironmentVariablesPropertySource(
                    useUnderscoresAsSeparator = false,
                    allowUppercaseNames = true,
                    environmentVariableMap = {
                        getEnv() +
                            mapOf("custom" to custom) 
                    },
                ),
            )
            .build()
            .loadConfigOrThrow<>(ADataClassWithConfigAlias)
```

Maybe nothing to deal with your MR?

**Comment by rocketraman** [comment]
> Actually we don't use yaml, as I said we use environment variables:
> 
> ```
> ConfigLoaderBuilder.default()
>             .addSource(
>                 EnvironmentVariablesPropertySource(
>                     useUnderscoresAsSeparator = false,
>                     allowUppercaseNames = true,
>                     environmentVariableMap = {
>                         getEnv() +
>                             mapOf("custom" to custom) 
>                     },
>                 ),
>             )
>             .build()
>             .loadConfigOrThrow<>(ADataClassWithConfigAlias)
> ```
> 
> Maybe nothing to deal with your MR?

Can you post the source of `ADataClassWithConfigAlias` please?

**Comment by laurentthiebaudezm** [comment]
We have for ex.

```
data class AMQPConfiguration(
    @ConfigAlias("amqpClientId") val clientId: String,
    @ConfigAlias("amqpHost") val hostName: String,
    @ConfigAlias("amqpPort") val portNumber: Int,
) 
```

If I rename variable `clientId` to `amqpClientId`, then it works well

**Comment by rocketraman** [comment]
> We have for ex.
> 
> ```
> data class AMQPConfiguration(
>     @ConfigAlias("amqpClientId") val clientId: String,
>     @ConfigAlias("amqpHost") val hostName: String,
>     @ConfigAlias("amqpPort") val portNumber: Int,
> ) 
> ```
> 
> If I rename variable `clientId` to `amqpClientId`, then it works well

@laurentthiebaudezm Thank you. And can you give me the exact form of the environment variable you are setting, including case? This example does not match the code snippet you provided above.

**Comment by laurentthiebaudezm** [comment]
We have

- AMQP_HOST
- AMQP_PORT
- amqpClientId (that we set manually like "custom" in my example)

Forgot to mention that `getEnv` is:

```
private fun getEnv(): Map<String, String> =
        dotenv { ignoreIfMissing = true }.entries().associate { it.key to it.value }
```

I don't remember why the ConfigAlias isn't the exact variable naming, probably hoplite can do some translation? Yet if I put the exact env variable name, it still doesn't work, e.g.

```
 @ConfigAlias("amqpHost") val hostName: String,
```

**Comment by rocketraman** [comment]
@laurentthiebaudezm Your issue is not the same cause as the one experienced by @sschuberth , but it is also related to new path normalizer in 2.8.

The problem is that the `ConfigAlias` value does not get normalized. And env vars go through an extra layer of manipulation i.e. the value `AMQP_HOST` is actually turned into a configuration `Node` with the key `amqpHost`, which is then normalized to `amqphost` by the path normalizer. This normalized value does not match the `ConfigAlias`.

Its a crappy workaround, but just to illustrate, if you set the `ConfigAlias` to the normalized value `amqphost` OR the actual source key `AMQP_HOST` it will work. The problem is in using the intermediate `amqpHost` value generated by the Environment property source.

I've updated the linked PR with a solution for this. Can you try it out?

**Comment by laurentthiebaudezm** [comment]
Hello that works well thank you!

**Comment by laurentthiebaudezm** [comment]
Hi do you plan to merge and release it? Looks like it is not in the last release :pray:

**Comment by laurentthiebaudezm** [comment]
Hi is there any chance to make a new release with the fix @sksamuel 🙏
