### ISSUE TITLE
Compile to Kotlin 1.8 instead of 1.6

### ISSUE THREAD

**Issue by rocketraman** [sksamuel/hoplite#459]
We currently compile against Kotlin 1.6.

I suggest we use the latest Kotlin compiler, and target Kotlin 1.8 using the compiler apiVersion and language version declarations. Jetbrain's policy is to support [3 previous language and API versions](https://kotlinlang.org/docs/kotlin-evolution-principles.html#compatibility-options), so it seems reasonable for Hoplite to do the same.

**Comment by sksamuel** [comment]
2.9.0 has been bumped to 1.9x with 2.1 about to be released.
So I'll close this now, we should follow the 3 previous rule moving forward.
