### ISSUE TITLE
Is there a way to load resources from build folder?

### ISSUE THREAD

**Issue by elizabetht** [sksamuel/hoplite#48]
I am using the gradle task "processResources" to process my templated "application.yml". This processed resource is available under "build/resources" folder. Is there a way to read this file instead of the resources file under "src/main/resources folder? Note: "application.yml" under "src/main/resources" fodler is templated and cannot be used for rendering the output in my controller/endpoint.

**Comment by sksamuel** [comment]
Is this while you are developing? When you deploy, the build/resources must get copied into your JAR or something ?

**Comment by elizabetht** [comment]
Yes, while developing..

**Comment by sksamuel** [comment]
You can load from a Path, rather than a resource file, so `ConfigLoader().loadOrThrow(Paths.get("./build/application.yml"))` or whatever the path is to your file.

Would that work ?

**Comment by elizabetht** [comment]
Sure thanks, that will work. I will give that a try!
