### ISSUE TITLE
Error resoliving jackson-bom when using maven

### ISSUE THREAD

**Issue by bbaldino** [sksamuel/hoplite#59]
Created a maven projected and depended on `hoplite-core` and `hoplite-json`, but something about the way `hoplite-json` expresses its dependency on `jackson-bom` seems to cause an issue, as maven complains it can't be found (even though it is pulled into the local maven repo).

![image](https://user-images.githubusercontent.com/4016469/64376258-b781c280-cfdc-11e9-991f-a2f2f10c7cb7.png)

**Comment by sksamuel** [comment]
This is fixed in 1.0.7
I've also added a sample project using maven here:
https://github.com/sksamuel/hoplite/tree/master/example-maven
