### ISSUE TITLE
Could not detect parser for file extension '.yaml'

### ISSUE THREAD

**Issue by 2x2xplz** [sksamuel/hoplite#94]
Building a Kotlin project in IntelliJ 2019.3.1 Community Edition. Trying to output a JAR artifact. My build.gradle has both of:
```
implementation 'com.sksamuel.hoplite:hoplite-core:1.1.3'  // hoplite for external config
implementation 'com.sksamuel.hoplite:hoplite-yaml:1.1.3'  // hoplite - yaml format
```
(also tried with 1.1.2) Yet I get the error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: com.sksamuel.hoplite.ConfigException: Error loading config because:

    Could not detect parser for file extension '.yaml' - available parsers are {props=com.sksamuel.hoplite.parsers.PropsParser@3d5c822d, properties=com.sksamuel.hoplite.parsers.PropsParser@3d5c822d}
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:141)
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:23)
        at arrow.core.ValidatedKt.valueOr(Validated.kt:734)
        at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:139)
        at api.MainKt.<clinit>(main.kt:130)
```
Because I have a `config.yaml` located in the resources folder, I can't run just `java -jar myapp.jar` but have to run `java -cp "myapp.main.jar;./resources" api.MainKt`  (I'm on Windows) Would that make a difference?

Everything runs just fine within IntelliJ. And to be fair, I have had all kinds of other problems getting IntelliJ to properly create a JAR ("no main manifest attribute", "Invalid signature file digest")

I'm out of ideas. I don't know Java well enough to diagnose. Like I said, it works fine when running inside of IntelliJ. I absolutely have the Hoplite-YAML library in my gradle.

**Comment by sksamuel** [comment]
You probably just need to build a "far jar". Look at
https://github.com/johnrengelman/shadow for example.

**Comment by 2x2xplz** [comment]
Thank you, the shadowJar plugin did solve a bunch of problems. Also a big help was compiling from the command line via gradle, rather than within IntelliJ.

One lingering issue, the current setup packages my config file inside the JAR. I was hoping that with hoplite I could have a external config file that I could edit independently of the JAR file. I experimented by manually removing it and placing the config file in the same directory, in `/resources`, and elsewhere in the root ClassPath but in all cases got the error `Could not find config file /config.yaml`

my code to load the file is simple: 
`val config = ConfigLoader().loadConfigOrThrow<Config>("/config.yaml")`

Is there a way to keep the config file outside of the JAR and still work? Thanks.

**Comment by sksamuel** [comment]
Yes, you can pass `Path`s rather than Strings. Strings are interpreted as resource paths.
So something like `val config = ConfigLoader().loadConfigOrThrow<Config>(Paths.get("/config.yaml"))`

**Comment by maroc81** [comment]
For anyone else who found their way here when trying to create a fat jar:  you have to use the shadow jar plugin in order to merge the service files used by hoplite to load the parsers.

See https://github.com/csolem/gradle-shadow-jar-with-kotlin-dsl/blob/master/build.gradle.kts for an example build.gradle.kts that uses ShadowJar with "mergeServiceFiles()".
