### ISSUE TITLE
env vars can not override values of sealed class

### ISSUE THREAD

**Issue by Globegitter** [sksamuel/hoplite#98]
Same examples as in #97, we provide a `default.config` file with some values, e.g.

```
database.host=localhost:5432
database.name=some_name
database.user=some_user
database.password=some_password
```

if I know provide some of those values through the env, so e.g. `DATABASE__USER` (using a custom property source to read these correctly) that works perfectly fine, but if I try to set

```
DATABASE__CONTENT={"host": "localhost", "port": 5432, "username": "test", "password": "test", "dbname": "test"}
```

I get the `Database.Text` data class with the values provided from `default.config`. If however I just comment out one line of the `default.config`, e.g. `database.user` then I get the `Database.Json` class as expected with the values provided from the env. I am just going to remove the default user and password config, as most likely it is useless anyway, but this is still surprising behaviour to me. Oh and I am loading the config as follows:

```
val config = ConfigLoader()
        .withDecoder(DatabaseSecretDecoder())
        .withPropertySource(CustomEnvironmentVariablesPropertySource)
        .loadConfigOrThrow<Config>("/default.properties")
```

**Comment by sksamuel** [comment]
You can't pass json into an ENV var and have hoplite pick up the env var as json and parse it. It would be too complex, you could be passing in yaml or toml or anything inside the env var.
Also your env vars must be in the same case as your config, so `database__pass`. 
Finally I added a test to confirm that you can override sealed class parameters with an env var and it seems to work fine.

**Comment by sksamuel** [comment]
https://github.com/sksamuel/hoplite/blob/master/hoplite-json/src/test/kotlin/com/sksamuel/hoplite/json/SealedClassTest.kt#L11-L17

**Comment by Globegitter** [comment]
@sksamuel Thanks for investigating, I have a custom decoder and property source that take care of the env variable naming as well as the json parsing, so that part is fine. 

The problem that I am having is not directly related to the json, but to reproduce the issue the test case you have written would also beed the password inside the json file but then use env vars to try and provide the full `Database.Elastic` config. Then the Database.Mysql will be set, even though I would have expected `Database.Elastic` to be set.

**Comment by sksamuel** [comment]
So if you had enough values to fulfil the Mysql subclass from a file, you would expect the Elastic subclass to be chosen if those values were available in the ENV  vars ?

**Comment by Globegitter** [comment]
Yeah, I did expect the env vars to have higher priority as that is how I understood the documentation here: https://github.com/sksamuel/hoplite#property-sources

**Comment by sksamuel** [comment]
Env vars will override other vars, but the whole "Tree" of values is created before deciding which subclass to use.

**Comment by VapidLinus** [comment]
This still seems to be an issue :/

```kotlin
val configResult = ConfigLoader.Builder()
    .addSource(PropertySource.file(File("config.toml"), optional = true))
    .addSource(PropertySource.resource("/default-config.toml"))
    .addDecoder(SnowflakeDecoder())
    .build()
    .loadConfig<Config>()

data class Config(
    val blankEmote: Emote,
    val totalMissCount: Int
)

sealed class Emote
data class UnicodeEmote(val name: String) : Emote()
data class GuildEmote(val id: Snowflake, @ConfigAlias("guild") val guildID: Snowflake) : Emote()
```

**default-config.toml**
```toml
total-miss-count = 7
blank-emote = { name = ":black_small_square:" }
```

**config.toml**
```toml
total-miss-count = 12
blank-emote = { id = "139498586236518441", guild = "153217084425764864" }
```

Here I expect the values in `config.toml` to take presedence over the values in `default-config.toml`. This happens for `total-miss-count` which is correctly evaluated to `12`, but blank-emote gets evaluated to `{ name = ":black_small_square:" }`.

This only seems to happen because `blank-emote` is `GuildEmote` in `config.toml` and `UnicodeEmote` in `default-config.toml`. If I change both to the same type, then presedence is again returned to `config.toml` as expected.

Is there a workaround for this? I expect all values in `config.toml` to take presedence even if the type changes.

**Comment by sksamuel** [comment]
Issue is something different - the sealed class type detection code is buggy. Opening a new ticket https://github.com/sksamuel/hoplite/issues/210
