### ISSUE TITLE
Empty properties file

### ISSUE THREAD

**Issue by TimothyEarley** [sksamuel/hoplite#99]
Attempting to load an empty .properties file causes an exception:

```
java.lang.RuntimeException: Bug: unsupported state. value is null and map is empty
	at com.sksamuel.hoplite.parsers.LoadPropsKt$toNode$2.invoke(loadProps.kt:34)
	...
```

Instead, I would like hoplite to parse an empty properties file as an empty map (and then fail later, when there are properties missing). The current exception is not very user-friendly.

To resolve the issue I have changed the line [loadProps.kt:34](https://github.com/sksamuel/hoplite/blob/7858c02e7155cbe254e7db7d14b05e3b0d07bd49/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/parsers/loadProps.kt#L34) to

```kotlin
      value == null && maps.isEmpty() -> MapNode(emptyMap(), pos)
```

As far as I can tell this doesn't break anything else. Is this the correct fix? I can also open a pull request if you'd like.

**Comment by sksamuel** [comment]
Yes that seems good, please PR.
